### PR TITLE
[utils module] [Test conversion] Injector test

### PR DESCRIPTION
**Pull request by hellosagar**
### Overview
Converted the [InjectorTest](https://github.com/hellosagar/robolectric/blob/d3330686a32c89f44e6e5d2b7ef5bab83843bfb0/utils/src/test/java/org/robolectric/util/inject/InjectorTest.kt)  from java to kotlin.

### Proposed Changes
In this, I've basically removed the java version `InjectorTest` and added the kotlin version.

### Current issue
 - Most test cases are working fine but for 2 test cases that are failing I'm still confused about why it's failing and I think it's related to the visibility issue and because lack of code understandability
 Screenshot 2022-04-09 at 8 40 34 PM

-  Another issue IDK how it works but when I put the two interfaces `Thing` and `Umm` separate in their own file test cases are passed but if I make them as a nested interface in `InjectorTest` tests are failing, I think its related visibility issue but the reason I don't exactly.

Mentors,  could you please help me with this - @hoisie @JuliaSullivanGoogle @dennismeng @utzcoz 
Thanks in advance :)

### CODE REVIEW

**Comment by utzcoz** [comment]
Looks like this is a compatibility problem between AutoService and Kotlin: https://stackoverflow.com/questions/46032368/kotlin-annotation-processor-cant-make-it-work. It's recommend to analyze it more to find the root cause and check whether we should keep it with Java. If you are not familiar with AutoService, you can read https://github.com/google/auto/tree/master/service for details.

**Comment by hellosagar** [comment]
I was in a doubt that its related visibility issue(public, protected and private related), Thanks for sharing I will check it out

**Comment by utzcoz** [comment]
@hellosagar could you analyze and try to fix this PR again? We can mark converting test codes of utils module finished after this PR merged.

**Comment by hellosagar** [comment]
@utzcoz I've learned about what ServiceLoader is and now that I know ServiceLoader, I checked that StackOverflow post that you shared - https://stackoverflow.com/questions/46032368/kotlin-annotation-processor-cant-make-it-work, basically Kotlin is ignoring the Autoservice tag. so, I've manually created an `org.robolectric.util.inject.MultiThing` file under META_INF/services and added the class which has its implementation
```
org.robolectric.util.inject.InjectorTest$MultiThingX
org.robolectric.util.inject.InjectorTest$MultiThingA
``

I'm also little lost on how fix this, could a little bit more about this, or the last option is we can keep this class in java

**Comment by hellosagar** [comment]
I've rebased the class against the latest merge and if its in Java the `utils` module all tests are passing

**Comment by utzcoz** [comment]
> I'm also a little lost on how to fix this, could you please guide little bit more about this, or the last option is we can keep this class in java

We can keep it as Java.

**Comment by utzcoz** [comment]
@hellosagar I will close this PR. Feel free to reopen it if you want to continue it.

**Comment by hellosagar** [comment]
Since we have to keep it in Java, so we can keep it closed as well

**Pull request closed without merging**
