### PR TITLE
Add RobolectricGradleTestRunner test runner implementation.

### PR DESCRIPTION
**Pull request by erd**
This class creates an AndroidManifest that is setup to match the defaults
used in the Android Gradle plugin and will allow you to run tests in
Android Studio.

### CODE REVIEW

**Comment by erd** [comment]
@ry4n1m3 I made a few simplifications that make it easier to run tests. I've also updated the 'gradle-test-runner' branch in the 'robolectric-samples' repo if you want to see it in action.

**Comment by nenick** [comment]
Did you try it with Android Studio? I guess there is still the issue with different execution root.

What do you think about use a custom property which could by add by 

    android {
      buildTypes {
        debug {
            buildConfigField "String", "MODULE_PATH", "\"$projectDir\""
        }
      }
    }

At runtime we check if the execution root contains the module folder. If yes then the location needs the leading MODULE_PATH else we use the default path. Gradle has the module path as execution root and Android Studio use the project root.

**Comment by erd** [comment]
@nenick For studio, I modified the default JUnit run configuration to set the working directory to '$MODULE_DIR$' which is effectively what Gradle does on the CLI. I came across an issue on the android issue tracker that seems to indicate this is a bug in studio (I'll see if I can dig up the link).

**Comment by nenick** [comment]
I know this open issue.

I like to see an option to use a workaround so we don't need to modify the run configuration. My opinion is that this would lead to a lesser barrier to use Robolectric.

**Comment by erd** [comment]
You're just trading one work-around for another. I feel that the test runner configuration is lower cost and is more easily removed when the AS bug is fixed. From the bug report, it also seems like this is an OSX bug only (Linux and Windows appear to work fine). Even if we went with the approach of adding another field to build.gradle, that would need to be documented as well (both solutions will confuse people and will need to be documented).

The reason that I'm pushing back is that there are a *ton* of workarounds in Robolectric for various build systems (project.properties file, library paths in @Config) and I really don't want to support another one :frowning:

**Comment by nenick** [comment]
Would be great the see a new snapshot release including this new class. Does something blocking this?

**Comment by erd** [comment]
The Travis build occasionally fails trying to download dependencies. I'll restart it.

**Pull request merged**
