### PR TITLE
Remove the redundant methods in ShadowLocation

### PR DESCRIPTION
**Pull request by hoisie**
### Overview

Remove the redundant methods in ShadowLocation

### Proposed Changes

Most of the methods in ShadowLocation were redundant because they were
clones of their Android counterparts. The only non-redundant method was
setDistanceBetween. Mark it as deprecated.

Also, add a LocationUtils class to assist in comparing two Location
objects. Overriding Location#equals subtly changes the behavior of the
native Location#equals method.

### CODE REVIEW

**Comment by hoisie** [comment]
The equals logic has been moved to LocationComparator. I'd be fine with adding it back, but isn't overriding the equals method undesirable, especially since Android's Location doesn't have an equals method? I recall a similar argument with Intent.

Is setDistanceBetween something that is widely used?

**Comment by xian** [comment]
Yeah, it's a fair point, we're subtly changing the behavior of `Location`... I'm thinking `setDistanceBetween()` isn't frequently used, and isn't really necessary. @jongerrish thoughts?

**Comment by xian** [comment]
#2782 was merged but accidentally reverted before 3.2; bumping this back to 3.4.

**Comment by hoisie** [comment]
ShadowLocation has been removed

**Pull request closed without merging**
