### PR TITLE
Remove empty ShadowTextPaint

### PR DESCRIPTION
**Pull request by utzcoz**
The implementation of `ShadowPaint#measureText` doesn't process text width correctly, and it can't be moved to ctesque.  And
`ShadowPaintTest#measureTextActuallyMeasuresLength` tests does the same thing that ShadowTextPaintTest does, so it's safe to remove `ShadowTextPaintTest`.

### CODE REVIEW

**Comment by utzcoz** [comment]
@hoisie Looks like `ShadowPaint#measureText` doesn't behavior as AOSP: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/graphics/java/android/graphics/Paint.java;l=2245-2266?q=Paint.java&ss=android. The `ShadowPaint#measureText` only care about text length, but doesn't care about text size.

**Comment by utzcoz** [comment]
And self-hosted runner broken again.

**Review by hoisie — APPROVED** [review]
Thanks! Weird how it was just an empty shadow.

**Comment by utzcoz** [comment]
> Thanks! Weird how it was just an empty shadow.

The commit https://github.com/robolectric/robolectric/commit/4dda01d613890b88a9370e46ec53ef54c123f9fb added `ShadowTextPaint` with `measureText` implementation. But I don't find relate commit to remove this implementation with `git blame $(find . -iname ShadowTextPaint.java)` and `git log -- $(ind . -iname ShadowTextPaint.java)`. The `ShadowPaint#measureText` implementation has the same function as old `ShadowTextPaint` one. Maybe one folk found this behavior, and remove it from `ShadowTextPaint` or move it to `ShadowPaint`.

**Pull request merged**
