### PR TITLE
Migrate compileSdkVersion to compileSdk

### PR DESCRIPTION
**Pull request by Akshay2131**
Overview
 
Migrated compileSdkVersion to compileSdk for Robolectric's tests.
Close: #6950  

Proposed Changes

Robolectric uses AGP 7.1.0 and starting from the release of AGP 7.0.0, we can use compileSdk instead of compileSdkVersion.
So, i changed compileSdkVersion to compileSdk.

### CODE REVIEW

**Comment by utzcoz** [comment]
@Akshay2131 This PR is separate, and don't need include changes from other PR. For example this PR includes changes about `ShadowContentResolver`, and this PR can't be merged before that PR merged and this PR rebased again.

**Comment by utzcoz** [comment]
@Akshay2131 After this PR, it's recommended to try non-starter issue of Robolectric. You have did some starter issues, and know how to contribute to Robolectric, and some rules of Robolectric needs for code. IMHO, starter issue is not suitable for you, and please leave it to other new contributors. Thanks for understanding.

**Comment by Akshay2131** [comment]
ok, i got it. Thanks @utzcoz

**Comment by utzcoz** [comment]
Hi @Akshay2131 , you can rebase this PR on latest master branch now. Your previous PR has been merged.

**Comment by utzcoz** [comment]
@Akshay2131 Looks like you don't rebase correctly.

**Comment by Akshay2131** [comment]
Actually,  i am closing this PR due to a lot of mess..
I will create a new one.

**Pull request closed without merging**
