### PR TITLE
Fix java encoding

### PR DESCRIPTION
**Pull request by jaredsburrows**
@xian @jongerrish Fix for https://github.com/robolectric/robolectric/issues/2558

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@xian @jongerrish I will rebase this soon.

**Comment by xian** [comment]
:-) you're awesome @jaredsburrows.

**Comment by jaredsburrows** [comment]
@xian No problem. This allows you to build all utf8 characters locally. I am building with jdk8.

**Comment by xian** [comment]
Any guess at why the jdk8 build takes half again as long as the jdk7 build?

**Comment by jaredsburrows** [comment]
It has to do with their container setup.
Take a look at this build for an app template: https://travis-ci.org/jaredsburrows/android-gradle-java-app-template

The xcode/mac osx template is nearly 1 minute faster than that of the linux/ubuntu.

**Comment by jaredsburrows** [comment]
The JDK7 passed but the JDK8 did not. This PR fixes the build so I can build Robolectric locally. This PR did not break the build.

**Comment by xian** [comment]
Huh. Maybe they get bound to a different class of builder machine or something? Weird.

Anyway, we got a build failure here, but I'm not sure why: https://travis-ci.org/robolectric/robolectric/jobs/145699274

**Comment by jaredsburrows** [comment]
@xian It has todo with their setup. Look at this app I have on CI with Travis: https://travis-ci.org/jaredsburrows/android-glide-giphy-example/jobs/140276479.

The tests fail with the said "exit 137".  But the same mac osx build works fine: https://travis-ci.org/jaredsburrows/android-glide-giphy-example/builds/140276478.

I combat these weird crashes by adding more memory:
https://github.com/jaredsburrows/android-glide-giphy-example/blob/master/.travis.yml#L5
and
https://github.com/jaredsburrows/android-glide-giphy-example/blob/master/.travis.yml#L32

**Comment by jaredsburrows** [comment]
@xian Can we get this in? I have to keep rebasing this.

**Comment by xian** [comment]
Thanks, I'll add more memory.

**Pull request merged**
