### PR TITLE
Use SHA-512 instead of SHA-1 in MavenArtifactFetcher

### LINKED ISSUE #7543: Suggest to support SHA512 and other modern metadata
### Description

Hi Robolectric,

Does Robolectric have a plan to support SHA512 and other metadata when it download a Android dependency jar from a maven?

Our office is blocked from an external network by a proxy and internal cert, so we used an offline mode to use a robolectric.
I tried to change it to download a Android dependency jar from our internal maven mirror, but it downloads only SHA512 metadata from a maven central.
So, when a robolectric tried to find a Android dependency jar from the maven mirror, it printed an error message that it can't find a metadata file from there.

If the latest robolectric already support it, I would appreciate it if you share a version to support it.

* Error message
```
SEVERE: Got more than one input Future failure. Logging failures after the first
java.io.FileNotFoundException: https://***/org/robolectric/android-all-instrumented/12-robolectric-7732740-i3/android-all-instrumented-12-robolectric-7732740-i3.jar.sha1
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1928)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.robolectric.internal.dependency.MavenArtifactFetcher$FetchToFileTask.call(MavenArtifactFetcher.java:190)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:160)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:143)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

* Internal maven mirror
```
android-all-instrumented-12-robolectric-7732740-i3-javadoc.jar->                -    -
android-all-instrumented-12-robolectric-7732740-i3-javadoc.jar.asc->            -    -
android-all-instrumented-12-robolectric-7732740-i3-javadoc.jar.asc.sha512->     -    -
android-all-instrumented-12-robolectric-7732740-i3-javadoc.jar.sha512->         -    -
android-all-instrumented-12-robolectric-7732740-i3-sources.jar->                -    -
android-all-instrumented-12-robolectric-7732740-i3-sources.jar.asc->            -    -
android-all-instrumented-12-robolectric-7732740-i3-sources.jar.asc.sha512->     -    -
android-all-instrumented-12-robolectric-7732740-i3-sources.jar.sha512->         -    -
android-all-instrumented-12-robolectric-7732740-i3.jar                      17-Nov-2021 23:20  135.70 MB
android-all-instrumented-12-robolectric-7732740-i3.jar.asc->                    -    -
android-all-instrumented-12-robolectric-7732740-i3.jar.asc.sha512->             -    -
android-all-instrumented-12-robolectric-7732740-i3.jar.sha512->                 -    -
android-all-instrumented-12-robolectric-7732740-i3.pom                      17-Nov-2021 23:20  1.36 KB
android-all-instrumented-12-robolectric-7732740-i3.pom.asc->                    -    -
android-all-instrumented-12-robolectric-7732740-i3.pom.asc.sha512->             -    -
android-all-instrumented-12-robolectric-7732740-i3.pom.sha512->                 -    -
```

### Steps to Reproduce

None

### Robolectric & Android Version

Robolectric: 4.7.3
Android: android-12

### PR DESCRIPTION
**Pull request by hoisie**
Use SHA-512 instead of SHA-1 in MavenArtifactFetcher

Fixes #7543

### CODE REVIEW

**Comment by utzcoz** [comment]
@hoisie What about syncing code between master and google branch? My previous commit https://github.com/robolectric/robolectric/commit/4ca787637ad4051b1aa17af0296ae1aa23e9e33c can help to reduce flakiness of Emulator tests by re-trying maximum three time if Emulator tests failed. It can't resolve all flaky Emulator tests on CI, but it can reduce our re-running actions manually.

**Review by utzcoz — APPROVED** [review]

**Comment by utzcoz** [comment]
Hi @hoisie , would this PR be merged soon?

**Comment by hoisie** [comment]
Yeah let me do some manual testing for this.

**Comment by hoisie** [comment]
ok seems to work fine, will merge it

**Pull request closed without merging**
