### PR TITLE
[Gradle] - Use Gradle api to find tools jar

### PR DESCRIPTION
**Pull request by jaredsburrows**
@jongerrish @xian

### CODE REVIEW

**Comment by hoisie** [comment]
Out of curiosity does this fix any issue or is it just cleanup?

**Comment by jaredsburrows** [comment]
@hoisie Clean up.

@jongerrish @xian Good to merge?

**Comment by jaredsburrows** [comment]
@hoisie Thanks for the merge. I didn't you had repo access as well!

**Comment by hoisie** [comment]
No problem! Thanks for cleaning this up. @jongerrish and @xian are out of town but will be back shortly.

**Comment by jaredsburrows** [comment]
@hoisie Thanks. For further updates and fixes, I'll make sure to CC you as well!

**Comment by xian** [comment]
Thanks @jaredsburrows!

**Comment by jaredsburrows** [comment]
@xian no problem!

**Pull request merged**
