### PR TITLE
Support Canvas#drawRect with RectF

### PR DESCRIPTION
**Pull request by Akshay2131**
Overview

Related to  PR : drawRect_toCanvas() added #7197 

Fixed the issue "Bitmap-backed canvas.drawRect fails with paint" https://github.com/robolectric/robolectric/issues/7188

 Proposed Changes

New methods and test cases added to support Rectangle drawing using paint in canvas.

### CODE REVIEW

**Comment by utzcoz** [comment]
@Akshay2131 Please follow https://github.com/robolectric/robolectric/wiki/Robolectric's-code-style to format your commits locally before pushing.

**Comment by hoisie** [comment]
Also https://github.com/robolectric/robolectric/wiki/Running-google-java-format

**Comment by utzcoz** [comment]
@Akshay2131 could you squash two commits to one? Thanks.

**Comment by Akshay2131** [comment]
@utzcoz Could you please review new commit?

**Review by utzcoz — APPROVED** [review]
LGTM. Thanks @Akshay2131.

**Comment by Akshay2131** [comment]
Thanks for your constant support @utzcoz  and @hoisie..
Looking forward to learn new things with you guys..

**Comment by hoisie** [comment]
Thanks @Akshay213!

**Pull request merged**
