### PR TITLE
Add Bundle options to ShadowPendingIntent

### PR DESCRIPTION
**Pull request by adaext**
Pass options to create function inside ShadowPendingIntent, so that we could get options through shadow.

### CODE REVIEW

**Review by utzcoz — APPROVED** [review]
LGTM. Thanks.

**Comment by utzcoz** [comment]
@adaext could you squash commits to one? Thanks.

**Comment by adaext** [comment]
> @adaext could you squash commits to one? Thanks.

Thanks for your advice. I've made it in the new commit.

**Comment by hoisie** [comment]
Thanks! Running these on some tests internally to check for any compatibility issues.

**Review by hoisie — APPROVED** [review]

**Pull request merged**
