### PR TITLE
Update build to use new gradle features from 4.5 on

### PR DESCRIPTION
**Pull request by xian**
- [ ] use new Gradle-style annotation processor declaration
- [ ] use new Gradle java-library plugin
- [ ] any other stuff we want?

### CODE REVIEW

**Comment by kageiit** [comment]
May want to use 4.6 now

**Comment by xian** [comment]
;-)

If anyone with more solid Gradle fu than me wants to take a stab at switching to the new annotation processor support, I'd be eternally grateful. :-)

**Comment by kageiit** [comment]
Ill do it if someone can finally merge this simple PR https://github.com/robolectric/robolectric/pull/3676 :P

**Comment by kageiit** [comment]
As promised - #3881 :)

**Pull request closed without merging**
