### PR TITLE
Only run jacoco-on-the-fly tests on Robolectric environment

### PR DESCRIPTION
**Pull request by utzcoz**

### CODE REVIEW

**Comment by ZSmallX** [comment]
Thanks for fix the tests, sorry for my PR broke the tests.

I recommend that removing the Android DSL and unnecessary dependencies by the way.

```
android {
    compileSdk 33

    defaultConfig {
        minSdk 16
        targetSdk 33
    }

    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }

    testOptions.unitTests.includeAndroidResources true
}

...

testImplementation "com.google.truth:truth:$truthVersion"
testImplementation "androidx.test:core:$axtCoreVersion"
testImplementation "androidx.test:runner:$axtRunnerVersion"
testImplementation "androidx.test.ext:junit:$axtJunitVersion"
testImplementation "org.jacoco:org.jacoco.agent:$jacocoVersion:runtime"
```

**Comment by utzcoz** [comment]
@ZSmallX you can send a new PR to fix it. This PR is just for testing.

**Comment by utzcoz** [comment]
@ZSmallX I decide to keep `AndroidProjectionConfiguration` and just move `robolectric` dependency to `testImplementation`. Sorry about it, I will merge this PR because I will rebase some PRs, and I need they can pass CI.

**Comment by ZSmallX** [comment]
OK, that's cool. As long as the integration tests don't break the CI workflow.

**Pull request merged**
