### PR TITLE
Prevent setting multiple cookies in a single call to RoboCookieManager#setCookie

### PR DESCRIPTION
**Pull request by utzcoz**
Refactor for https://github.com/robolectric/robolectric/pull/5964. Only rebasing, and fixing merge conflict.

### CODE REVIEW

**Comment by utzcoz** [comment]
@Khang-NT doesn't response to resend it after one month, so I do it to make it merged more quickly. I don't know why CircleCI doesn't work for recently PRs. Hi @hoisie, could you help to review this PR? Thanks.

**Comment by utzcoz** [comment]
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/webkit/CookieManager.java;l=100-120?q=CookieManager The comment says `CookieManager#setCookie` only processes one cookie, and the user should call this method multiple times if user wants to set multiple cookies.

**Comment by utzcoz** [comment]
Hi @hoisie , could you help to review this refactor PR? Thanks.

**Comment by hoisie** [comment]
Sure, sorry for the delay. Running it internally to get a sense if there are any issues.

**Comment by hoisie** [comment]
I believe there's one small issue with this. If you call setCookie with something like `ID=test-id; path=/; domain=.domain.com`, the result of getCookie is only `ID=test-id`. I haven't verified what real Android does in this situation.

**Comment by hoisie** [comment]
These seem to be the valid attributes on set-cookie:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

**Comment by utzcoz** [comment]
> https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/webkit/CookieManager.java;l=100-120?q=CookieManager The comment says `CookieManager#setCookie` only processes one cookie, and the user should call this method multiple times if user wants to set multiple cookies.
> 

From the comment, this API only supports set one cookie item every calling, and the user should call it multiple times to set multiple cookie items. It's better to add a test to ctsque to test this behavior on official emulator, and I will do it with new commit. cc @hoisie

**Comment by hoisie** [comment]
Yes one cookie at a time, but I believe `Set-Cookie: ID=test-id; path=/; domain=.domain.com` counts as one cookie

**Comment by utzcoz** [comment]
> Yes one cookie at a time, but I believe `Set-Cookie: ID=test-id; path=/; domain=.domain.com` counts as one cookie. The path and domain are attributes of the cookie.

Thanks. I reread Mozilla doc, and I think I know the real meaning of your problem. I will create new tests for it to check it.

**Comment by utzcoz** [comment]
> I believe there's one small issue with this. If you call setCookie with something like `ID=test-id; path=/; domain=.domain.com`, the result of getCookie is only `ID=test-id`. I haven't verified what real Android does in this situation.

I tested it on official emulator, and the test result is `ID=test-id`. The following code snippet is my test code:

```java
    @Test
    public void setCookie_shouldSupportMultiAttributes() {
        final String httpsUrl = "https://robolectric.org/";
        final CookieManager cookieManager = CookieManager.getInstance();
        cookieManager.setCookie(httpsUrl, "ID=test-id; path=/; domain=.robolectric.org");
        String cookie = cookieManager.getCookie(httpsUrl);
        assertThat(cookie).isEqualTo("ID=test-id");
    }
```

The `path` and `domain` are attributes, and it will affect the cookie owner.

**Comment by utzcoz** [comment]
The [setCookie doc](https://developer.android.com/reference/android/webkit/CookieManager#setCookie(java.lang.String,%20java.lang.String)) says it follows [rfc6265bis](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-03), the similar/same spec with https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie. They define many attributes, including above mentioned `path`, `domain`, `max-age` and others. But `Robolectric`'s `RoboCookieManager` only supports some of them, including `expires` and `secure`. So the following test will pass on emulator, but failed with `Robolectric`:

```java
  @Test
  public void setCookie_shouldReturnsNullForNonEqualsURL() {
    final String httpsUrl = "https://robolectric.org/";
    final CookieManager cookieManager = CookieManager.getInstance();
    cookieManager.setCookie(httpsUrl, "ID=test-id; path=/some/path; domain=.other.org");
    String cookie = cookieManager.getCookie(httpsUrl);
    assertThat(cookie).isNull();
  }
```

If we want to improve the fidelity of `Robolectric`'s `CookieManager` implementation, we should support other cookie header attributes on `Robolectric`. Because `Robolectric` runs on JVM, we can try to use `HttpCookie` as backend of `RoboCookieManager` to parse and check cookie header. And we can copy [CookieManagerTest](https://cs.android.com/android/platform/superproject/+/master:cts/tests/tests/webkit/src/android/webkit/cts/CookieManagerTest.java) from cts to our `ctsque` module to test the implementation. I think it is a good thing to implement, but I want to try it. What do you think about it @hoisie ?

**Comment by utzcoz** [comment]
From [HttoCookie doc](https://docs.oracle.com/javase/9/docs/api/java/net/HttpCookie.html), it supports three RFCs about cookie header: 

    Netscape draft
    RFC 2109 - http://www.ietf.org/rfc/rfc2109.txt
    RFC 2965 - http://www.ietf.org/rfc/rfc2965.txt 

The [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265) obsoletes [RFC 2965](http://www.ietf.org/rfc/rfc2965.txt), and [RFC 6265 BIS](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-03#page-23) obsoletes  [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265). Because [RFC 6265 BIS](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-03#page-23) is on the draft state, the newest is [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265). I found there are some bugs of `HttpCookie` related to [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265) compatibility, such as https://bugs.openjdk.java.net/browse/JDK-8206092. I don't know those compatibility problems can be accepted. And I found a project called [java-cookie](https://github.com/js-cookie/java-cookie) that supports [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265). For me, I prefer to `HttpCookie` with less security problems, and handle those compatibility problems with patch code.

**Comment by hoisie** [comment]
Thanks for the detailed investigation. The situation with RoboCookieManager is definitely not great. I think this as a short-term fix is fine. Longer term we can look into using something more official. I'll start the process of merging this today.

**Pull request merged**
