### PR TITLE
Fix for issue #1711: automatically execute runnables when not paused

### PR DESCRIPTION
**Pull request by kriegfrj**
Also fixed another bug I found where the clock was not being advanced in the "idling constantly" mode, and added some Javadoc explaining the difference between "idle constantly", unpaused, and paused operation.

See #1711 for a discussion of why I felt this PR was necessary. Hopefully this solution keeps everyone happy.

### CODE REVIEW

**Comment by laminina** [comment]
hi @kriegfrj thanks a lot for investing time no this!
I pulled your commits, played as well around BackgroundScheduler and UIScheduler as well (with nesting Runnables) and don't see anything odd so far, just want it to let you know :)

**Comment by charlesmunger** [comment]
I think this behavior is incorrect, and should probably be reverted. Consider this case:

    int i = 3;
    test() {
        postOnUiThread(new Runnable() {
            i++;
        });
        println(i);
    }

In a unit test, this code prints "4". In production, it prints "3". While it is attractive to "unpause" the looper, that's not really what's happening - the posted events aren't being run automatically, they're being run *inline*. The difference is subtle, but annoying (when tests break) and dangerous (when production breaks, because tests weren't faithfully emulating production).

**Comment by erd** [comment]
I'm not opposed to changing how the schedulers work with respect to paused and un-paused, but that would be a huge change and probably bigger than what's being discussed here. There are other parts of the system that rely on runnables being executed immediately for un-paused schedulers (like `ActivityController`) and they made need re-work if we changed it.

The way I've always used this functionality is that if I care about the execution ordering of tasks in the scheduler, I'll pause the scheduler, do something that enqueues some tasks, then run one job at a time and observe the effects of the tasks.

**Comment by kriegfrj** [comment]
Hi @charlesmunger, thanks for the feedback!

I tend to agree with @erd. This PR was about making nested runnables execute in a manner (whether that be to run inline or to get queued) that is *consistent* with non-nested runnables (which is historically how it worked prior to the implementation of the fix for #919). Your concern seems to apply more generally to whether posted runnables should ever be run inline, or if they should always be queued (whether they are nested or not), which is a bit beyond this PR. (To put it another way, this PR tries to restore historical behaviour; you're arguing that the historical behaviour was incorrect to begin with.)

There is already an open issue which I think accurately describes the concern that you have raised (#1306). I have developed some thoughts on this in recent weeks but rather than comment in detail here I might offer an opinion on #1306 to keep it all together (and perhaps you might do the same). In the meantime, suffice it to say that for most situations I find the default unpaused behaviour is very convenient, and for those situations where I need to 100% faithfully emulate & test real Android scheduling behaviour I do what @erd said (ie, pause the scheduler and drive it manually). Hope that helps!

**Pull request merged**
