### PR TITLE
Workaround for AGP not merging test manifest

### PR DESCRIPTION
**Pull request by xian**
Since #4489, Robolectric no longer automatically creates manifest entries for unknown activities, which has led to issues like #4649 and #4640. That's the desired behavior (it's how real Android devices work); however, it should be possible for test authors to declare test-only activities in a test manifest. Unfortunately, Android Gradle Plugin 3.4 (and prior) doesn't merge manifests declared in `src/test` (see #4726 tracking a fix for that).

This is a workaround for Android Gradle Plugin's failure to merge test manifests.

In order to use test-only activities, you can create a test support gradle project which contains the test activity and declares it in its manifest, then add a `testImplementation` dependency to to that project. Your dependency graph will be `app(test)` -> `testsupport(main)` -> `app(main)`.

`app/build.gradle`:
```groovy
dependencies {
  testImplementation ":testsupport"
}
```

`testsupport/build.gradle`:
```groovy
dependencies {
  implementation ":app"
}
```

See changes for more details.

### CODE REVIEW

**Comment by goldy1992** [comment]
Please note that this **will only work** if your **app module** is an **android library**. This is because module dependencies can only be libraries and not applications.

**Comment by arekolek** [comment]
This workaround does not work for me with 4.3.1 when I try to set an `<application android:name` in tests. But it does work with 4.4-SNAPSHOT.

Here's my code: https://github.com/robolectric/robolectric/compare/master...arekolek:test-manifest-application-name?expand=1

Can I somehow make this work with a stable version?

**Comment by goldy1992** [comment]
This approach should not be used any more....
The correct approach if to use **android flavors** (see https://developer.android.com/studio/build/build-variants)
Create a separate flavor such as "integration" for integration tests and put the test activities in that flavor's source directory.
For your actual androidTests, create a directory called androidTestIntegration and put your tests there.

**Comment by Allen-HiCharlie** [comment]
I ran into this issue and the solution was to make sure my gradle file contained the line:
`debugImplementation 'androidx.fragment:fragment-testing:1.2.5'`

**Comment by kassim** [comment]
> I ran into this issue and the solution was to make sure my gradle file contained the line:
> `debugImplementation 'androidx.fragment:fragment-testing:1.2.5'`

This indeed solves the issue for the missing `FragmentScenario$EmptyFragmentActivity` class. Unfortunately I have a requirement of testing against release builds, and we definitely don't want to include the `fragment-testing` lib in the release build.

I think goldy1992's solution of having multiple flavours will keep the builds the cleanest, but it does produce an annoying complexity

**Comment by goldy1992** [comment]
I've not tried yet but maybe [dagger hilt](https://github.com/google/dagger/releases) could help out here. Essentially you can organise dependencies into modules and for your tests, uninstall the original modules and replace them with the test dependencies.

**Comment by jonathanarodr** [comment]
Hello every one,
@DHosseiny I'm resolved this problem adding the dependency in my gradle similar the [documentation](https://developer.android.com/guide/fragments/test?authuser=1#declare-dependencies)

```gradle
debugImplementation "androidx.fragment:fragment-testing:$fragment_version"
```

**Comment by rasmusohrstig** [comment]
Has anyone else tried to work around this problem by adding a manifest in the debug folder? Seems to work for me. Like this, in **myapp/scr/debug/**

`
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <application>

        <activity android:name="com.mycompany.myapp.MyTestActivity" android:exported="true" />
    </application>
</manifest>
`

This assumes that you have a single TestActivity that you use for all your tests.

This will naturally not work for release builds. I guess it should be possible to create a Gradle plugin that modifies the manifest, but I have not tried that.

**Comment by xyzwilliamxyz** [comment]
I received this same error message, but in my case it was missing this on build.gradle:
```
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
```

**Comment by leggomymeggos** [comment]
@xyzwilliamxyz Thank you for commenting, this was also my issue. For anyone else, you need this in the `build.gradle` of the main module, not the `:testsupport` module

**Comment by alwa** [comment]
I'm getting this all the time when running tests for Jetpack Compose on MacOS (tests pass on Windows).
My tests are constructed in this way: https://stackoverflow.com/q/70592612/1859486

```
java.lang.RuntimeException: Unable to resolve activity for Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.mycompany/androidx.activity.ComponentActivity } -- see https://github.com/robolectric/robolectric/pull/4736 for details
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.startActivitySyncInternal(RoboMonitoringInstrumentation.java:90)
        at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:[33](https://sourcery.assaabloy.net/emeia/cliq/apps/cliq-connect-android/-/jobs/739249#L33))
        at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:38)
        at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:271)
        at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:197)
        at androidx.test.ext.junit.rules.ActivityScenarioRule.lambda$new$0$ActivityScenarioRule(ActivityScenarioRule.java:70)
        at androidx.test.ext.junit.rules.ActivityScenarioRule$$Lambda$0.get(ActivityScenarioRule.java:70)
        at androidx.test.ext.junit.rules.ActivityScenarioRule.before(ActivityScenarioRule.java:103)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
        at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1$evaluate$1.invoke(AndroidComposeTestRule.android.kt:145)
        at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1$evaluate$1.invoke(AndroidComposeTestRule.android.kt:144)
        at androidx.compose.ui.test.AndroidComposeTest.withAndroidComposeTest(ComposeTest.android.kt:235)
        at androidx.compose.ui.test.AndroidComposeTest.access$withAndroidComposeTest(ComposeTest.android.kt:61)
        at androidx.compose.ui.test.AndroidComposeTest$runTest$1$1$1$1$1$1$1.invoke(ComposeTest.android.kt:132)
        at androidx.compose.ui.test.AndroidComposeTest.withTextInputService(ComposeTest.android.kt:304)
        at androidx.compose.ui.test.AndroidComposeTest.access$withTextInputService(ComposeTest.android.kt:61)
        at androidx.compose.ui.test.AndroidComposeTest$runTest$1$1$1$1$1$1.invoke(ComposeTest.android.kt:131)
        at androidx.compose.ui.test.AndroidComposeTest.withComposeIdlingResource(ComposeTest.android.kt:291)
        at androidx.compose.ui.test.AndroidComposeTest.access$withComposeIdlingResource(ComposeTest.android.kt:61)
        at androidx.compose.ui.test.AndroidComposeTest$runTest$1$1$1$1$1.invoke(ComposeTest.android.kt:130)
        at androidx.compose.ui.test.AndroidComposeTest.withWindowRecomposer(ComposeTest.android.kt:265)
        at androidx.compose.ui.test.AndroidComposeTest.access$withWindowRecomposer(ComposeTest.android.kt:61)
        at androidx.compose.ui.test.AndroidComposeTest$runTest$1$1$1$1.invoke(ComposeTest.android.kt:129)
        at androidx.compose.ui.test.AndroidComposeTest.withTestCoroutines(ComposeTest.android.kt:278)
        at androidx.compose.ui.test.AndroidComposeTest.access$withTestCoroutines(ComposeTest.android.kt:61)
        at androidx.compose.ui.test.AndroidComposeTest$runTest$1$1$1.invoke(ComposeTest.android.kt:128)
        at androidx.compose.ui.test.junit4.IdlingStrategy$DefaultImpls.withStrategy(IdlingStrategy.android.kt:52)
        at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy.withStrategy(RobolectricIdlingStrategy.android.kt:39)
        at androidx.compose.ui.test.AndroidComposeTest$runTest$1$1.invoke(ComposeTest.android.kt:127)
        at androidx.compose.ui.test.junit4.IdlingResourceRegistry.withRegistry(IdlingResourceRegistry.jvm.kt:157)
        at androidx.compose.ui.test.AndroidComposeTest$runTest$1.invoke(ComposeTest.android.kt:126)
        at androidx.compose.ui.test.junit4.ComposeRootRegistry.withRegistry(ComposeRootRegistry.android.kt:146)
        at androidx.compose.ui.test.AndroidComposeTest.runTest(ComposeTest.android.kt:125)
        at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1.evaluate(AndroidComposeTestRule.android.kt:144)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:8[34](https://my-ci-server/-/jobs/739249#L34))
```

**Comment by realdadfish** [comment]
Weirdly enough using `testImplementation` for a module containing a test activity to be present at test execution time in Robolectric works for me in recent AGP versions (I am on 7.2.0-beta04) when used in _library modules_, but not in _application modules_.

**Comment by jdemeulenaere** [comment]
Note that for Compose the right way to fix this seems to be to depend on `androidx.compose.ui:ui-test-manifest` as explained in https://developer.android.com/jetpack/compose/testing#setup. This simple library just exports the ComponentActivity in its manifest [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-test-manifest/src/main/AndroidManifest.xml) so you don't have to do it yourself.

**Comment by neworld** [comment]
@realdadfish, I am investigating a very similar problem, but I am using AGP 7.1. The same test class moved to the library module works just fine, but in application not. 

I found some discussion about `application vs library` behavior, which could be related: https://issuetracker.google.com/issues/127986458#comment10

**Comment by polson** [comment]
Here is another workaround you can use to register your test activity.  Just do this before launching it when using `ActivityScenario`

```
        val appContext: Application = ApplicationProvider.getApplicationContext()
        val activityInfo = ActivityInfo().apply {
            name = TestActivity::class.java.name
            packageName = appContext.packageName
        }
        shadowOf(appContext.packageManager).addOrUpdateActivity(activityInfo)
```

**Comment by beshoy-samy** [comment]
for people like me coming nowadays if adding `debugImplementation("androidx.compose.ui:ui-test-manifest:$compose_version")` is not working make sure you have this line added too
`testOptions.unitTests.isIncludeAndroidResources = true` to the android section in the gradle file otherwise you would spend hours debugging not knowing what is happening really 😅

**Pull request merged**
