### PR TITLE
Delete most of ShadowIntent in favor of real android

### LINKED ISSUE #1913: Intent.cloneFilter doesn't actually clone the intent's Action

### PR DESCRIPTION
**Pull request by charlesmunger**
Fixes #1913

This does remove a few extra methods that were on ShadowIntent. Are we OK with removing that public API?

### CODE REVIEW

**Comment by jongerrish** [comment]
Looks good to me. Its always nice to remove shadow code.

**Comment by mag** [comment]
Awesome. If this is intended for 3.0, I have no problem removing the public methods - they were @Deprecated, after all.

**Comment by erd** [comment]
There seems to be a bunch of related test failures. Could you take a look?

ShadowIntentTest.shouldSupportCategories:302 NullPointer
ShadowIntentTest.shouldSupportCategories:302 NullPointer
ShadowIntentTest.shouldSupportCategories:302 NullPointer
ShadowIntentTest.shouldSupportCategories:302 NullPointer
ShadowIntentTest.shouldSupportCategories:302 NullPointer
ShadowActivityTest.startActivity_shouldDelegateToStartActivityForResult:128 » Runtime
ShadowActivityTest.startActivityForResultAndReceiveResult_shouldSendResponsesBackToActivity:145 » Runtime

**Comment by charlesmunger** [comment]
So for some reason, I can't reproduce those failures locally. (Is there some way to make maven *actually*  build my source files?)

But the failures are actually pretty pernicious - Intent, in real android, doesn't implement `equals` or `hashcode`. Running in robolectric tests, it does! I think this is a big mistake, as a Set<Intent> will behave very differently in production vs in unit tests. However, this change will probably break tests that are depending on the incorrect behavior. Are we OK with that?

**Comment by erd** [comment]
> Is there some way to make maven actually build my source files?

Run `./scripts/install-robolectric.sh` - it will do a full build and run all the tests.

**Comment by jongerrish** [comment]
@charlesmunger I agree, we should remove the equals and hashcode. We did the same for Bitmap recently and while it broke a few tests, I think it was the right thing to do to be closer to real Android and remove shadow code.

**Pull request merged**
