### PR TITLE
Deploy scripts create and upload shadows-core jars for API 22 and 23

### PR DESCRIPTION
**Pull request by mag**
I got 3.1-rc1 built and deployed to a staging repository on Sonatype. But when I tried to use API 23 I got a failure - the shadows jar (for 23) was not available.

Turns out the release deploy script (deploy-release.sh) does not build the shadows-core jars for 22 or 23.  So in this PR I updated it to build these jars and upload them.

As far as change to build-snapshot.sh - it was also missing lines for 22 and 23. Maybe not necessary; I am not sure how the snapshot build is actually getting those up to Sonatype, but they are there (https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/shadows-core/3.1-SNAPSHOT/). 

Regardless I updated deploy-snapshot.sh along with deploy-release.sh despite the fact that I don't understand how this stuff works.

I tested the resulting release build via the staging repository on Sonatype and things generally work in terms of dependencies being satisfied. Once I get this changed merged to master I will continue with the process of releasing 3.1 RC1.

Let me know if any of this seems fishy.

### CODE REVIEW

**Comment by mag** [comment]
Travis is failing; it looks like they've been failing since @jongerrish merged #2369. Any ideas what's going on Jonathan?

**Comment by jongerrish** [comment]
It looks like it's been super flaky since that PR, I'll take a look today. Let's just kick off a build again and retry.

**Comment by erd** [comment]
> Regardless I updated deploy-snapshot.sh along with deploy-release.sh despite the fact that I don't understand how this stuff works.

`deploy-snapshot.sh` is used by the `.travis.yml` build script to build and deploy SNAPSHOT builds.

`deploy-release.sh` can be run manually to build and deploy a release build (this is what I used to build the 3.0 release).

The scripts exist because simply building with `mvn compile` only builds the most recent version of the `shadows-core` artifact. The scripts build the required artifacts in the right order (with the right profiles). Updating both to support API 22 and 23 is a good idea.

**Comment by jongerrish** [comment]
Want to merge with master?

**Comment by mag** [comment]
Yes I will do so today.

**Pull request merged**
