### PR TITLE
Use unistd.h methods to replace mman.h for native SQLite backend on Windows

### PR DESCRIPTION
**Pull request by utzcoz**
`CursorWindow` use memory to allocate `mHeader` directly, instead of `ashmem`.

### CODE REVIEW

**Comment by hoisie** [comment]
Very cool! Excited to see how this works out :)

**Comment by utzcoz** [comment]
Actually I want to delete `libcutil`, including `ashmem` only, but `robo_android_database_SQLiteConnection.cpp` uses it to allocate memory for region data. Current `libcutil` uses temporary file as backend for `ashmem`. Maybe we can `File` operation to replace `map` and `munmap` to leverage data created by `ashmem` APIs. We can add new APIs to convert `ashmem` to File or byte data. I also found `ashmem` maybe used for sharing data(https://github.com/robolectric/robolectric/blob/master/nativeruntime/cpp/androidfw/CursorWindow.cpp#L99), and it can be used for later APIs support.

**Comment by utzcoz** [comment]
> Very cool! Excited to see how this works out :)

Current patch is very simple: using `new` and `delete` to create/destroy `mHeader` for `CursorWindow`. `CursorWindow` uses mmapped fd to get buffer region, and casts it to `mHeader` before. It is a very simple `struct`, we can replace it with in-memory method directly. Actually I want to leverage ashmem fd at later version, but with `File` API instead of `sys/mman.h` APIs.

**Comment by utzcoz** [comment]
`robo_android_database_SQLiteConnection.cpp` also uses `sys/mman.h` to map/munmap file descriptor(fd) at `createAshmemRegionWithData`. This method is used by `SQLiteConnectionNatives#nativeExecuteForBlobFileDescriptor`, used at https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/database/sqlite/SQLiteConnection.java;l=845-846?q=nativeExecuteForBlobFileDescriptor. I don't know whether the support for this API is necessary. If not, we can returns -1 from this native implementation; If yes, maybe we need to bind our native ashmem implementation to frameworks APIs.

**Comment by utzcoz** [comment]
Hi @hoisie , I updated PR with unistd.h methods(read and write) to replace mman.h for native SQLite. Looking forward your suggestion about it. I will test it with Windows building tomorrow.

**Comment by hoisie** [comment]
Is there a way to keep using mman.h on Linux and Mac, and have alternative implementations on Windows using a combination of `#ifdef _WIN32` and `#ifdef __linux__`. In general I'd rather have Windows use fakes for now instead of converting Mac and Linux to use fakes as well.

**Comment by utzcoz** [comment]
> Is there a way to keep using mman.h on Linux and Mac, and have alternative implementations on Windows using a combination of `#ifdef _WIN32` and `#ifdef __linux__`. In general I'd rather have Windows use fakes for now instead of converting Mac and Linux to use fakes as well.

No problem. I will update patch today to add `#ifdef _WIN32`.

**Comment by utzcoz** [comment]
Looks like there are lot of things to support building on Windows. I merge this PR to https://github.com/robolectric/robolectric/pull/6801. If I can't make it work on Windows, this PR can't be merged. Hi @hoisie , I will continue this work at https://github.com/robolectric/robolectric/pull/6801.

**Pull request closed without merging**
