### PR TITLE
Set ServiceInfo.processName from ApplicationInfo.processName.

### LINKED ISSUE #4090: Fake ServiceInfo doesn't contain processName, causing LeakCanary failure
### Description
Unit tests ran with `RobolectricTestRunner` fail with the following exception:
```java
java.lang.NullPointerException
	at com.squareup.leakcanary.internal.LeakCanaryInternals.isInServiceProcess(LeakCanaryInternals.java:114)
	at com.squareup.leakcanary.LeakCanary.isInAnalyzerProcess(LeakCanary.java:182)
	at com.squareup.cash.CashApp.onCreate(CashApp.java:45)
        ...
```

The stack trace points to the following code in [LeakCanary](https://github.com/square/leakcanary) codebase:
```java
ComponentName component = new ComponentName(context, serviceClass);
ServiceInfo serviceInfo;
try {
  serviceInfo = packageManager.getServiceInfo(component, 0);
} catch (PackageManager.NameNotFoundException ignored) {
  // Service is disabled.
  return false;
}

// this line causes the crash
if (serviceInfo.processName.equals(mainProcess)) {
```

Debugging shows that the value of `processName` is null.

### Robolectric & Android Version
Robolectric: 4.0.1
Android: compileSdk = 28, targetSdk = 28, minSdk = 21

### PR DESCRIPTION
**Pull request by xian**
Fixes #4090.

### CODE REVIEW

**Comment by xian** [comment]
Cleaned up and added a hack for pre-P.

**Comment by xian** [comment]
Merged to `robolectric-4.0.x` also.

**Comment by Egorand** [comment]
That was fast, thanks!

**Comment by Ce234** [comment]
What if the Service is registered in the AndroidManifest with another process name ? Does ServiceInfo.processName will simply return the App process name and not the one registered in the AndroidManifest with the android:process attribute ? I ask this because a library is causing a crash because their code expect a specific process name set in Manifest

**Pull request merged**
