### PR TITLE
update README file

### PR DESCRIPTION
**Pull request by HJXANDHMR**
### Proposed Changes

update @Config(constants = BuildConfig.class,sdk = 21)

### CODE REVIEW

**Comment by HJXANDHMR** [comment]
update is README.md file update @Config(constants = BuildConfig.class,sdk = 21)

**Comment by mag** [comment]
I'm worried this will mislead people to believe that 'sdk' is required. Don't forget, we have http://robolectric.org/configuring/.

**Comment by erd** [comment]
As @mag mentioned, setting `sdk` is not required as Robolectric will default to the `targetSdk` value in your manifest. Additionally, we have the configuring docs that cover manually setting the sdk value.

**Comment by HJXANDHMR** [comment]
If you do not set the SDK, the program will be reported to the wrong

**Pull request closed without merging**
