### PR TITLE
Errorprone and google format fix annotation module

### PR DESCRIPTION
**Pull request by hellosagar**
### Overview
Fixed the error-prone warning and added the google java style format for the annotations module

### Proposed Changes
So, the only error warning for the annotation module was `UnrecognisedJavadocTag`, and I've fixed that by converting the comment from previously this:
```
@see {@link org.robolectric.plugins.LooperModeConfigurer}, {@link org.robolectric.util.Scheduler}, {@link org.robolectric.shadows.ShadowLooper}
 ```
 
 to this now:
``` 
* @see org.robolectric.plugins.LooperModeConfigurer
* @see org.robolectric.util.Scheduler
* @see org.robolectric.shadows.ShadowLooper
 ```
 
 Which has the same effect on Javadoc rendering
 
 and other than this its mostly, the google's java format style changes

### CODE REVIEW

**Comment by utzcoz** [comment]
@hellosagar could you rebase your PR on latest master branch and remove your "Merge branch" commit? Thanks.

**Comment by hellosagar** [comment]
@utzcoz i don't know exactly how to delete the merge branch commit from this PR, so I closed this and open the new one #7154

**Comment by hellosagar** [comment]
is there is a way to remove the "merge branch" commit from the current branch besides using the force commit?

**Comment by utzcoz** [comment]
@hellosagar I have shown my example at https://github.com/robolectric/robolectric/pull/7154#issuecomment-1073016873.

**Pull request closed without merging**
