### PR TITLE
Simplify removeFrameCallback() to use Handler

### PR DESCRIPTION
**Pull request by lexs**

### CODE REVIEW

**Comment by kriegfrj** [comment]
Have we tried gutting ShadowChoreographer and relying on the real Android code to do the scheduling? A quick glance at the Android code suggests it might work?

**Comment by erd** [comment]
We created `ShadowChoreographer` out of necessity to make certain types of animations work. It might be possible to pare it down, but some parts are necessary.

**Comment by lexs** [comment]
Test failure is flake btw:

    [ERROR] Plugin org.robolectric:robolectric-velocity-plugin:1.1.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.robolectric:robolectric-velocity-plugin:jar:1.1.0: Could not transfer artifact org.robolectric:robolectric-velocity-plugin:pom:1.1.0 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]

**Comment by kriegfrj** [comment]
Yes @erd, I figured some of `ShadowChoreographer` will probably still be necessary, but I wonder if the native post methods can be left alone to do their thing at least. I don't have time to look into this at the moment so I'll leave that to your judgement; just making the suggestion.

**Pull request merged**
