### PR TITLE
Add CI job to build nativeruntime for Windows

### PR DESCRIPTION
**Pull request by utzcoz**
For https://github.com/robolectric/robolectric/issues/6791.

### CODE REVIEW

**Comment by utzcoz** [comment]
It must wait https://github.com/robolectric/robolectric/issues/6791.

**Comment by utzcoz** [comment]
I found a very strange problem: the cache restored, but restored icu-bin doesn't have generated .a files.

**Comment by utzcoz** [comment]
Looks like I should find a method to pass value to `$GITHUB_ENV` at `msys2` environment. It's closer to the target. I will take a look at tomorrow.

**Comment by utzcoz** [comment]
> Looks like I should find a method to pass value to `$GITHUB_ENV` at `msys2` environment. It's closer to the target. I will take a look at tomorrow.

I decided to use hard-coded file name to replace `GITHUB_ENV` for uploading step for Windows.

**Comment by utzcoz** [comment]
> I found a very strange problem: the cache restored, but restored icu-bin doesn't have generated .a files.

I updated cache key with adding `cache-v2` to fix this problem for macOS and Linux. But cache doesn't work for Windows with msys2 now. So I let job to build ICU for Windows forcibly temporarily.

**Comment by utzcoz** [comment]
There is another weird problem: Windows generated dll file is small, about 5~6MB, less than other platforms' file size: about 30MB.

**Comment by utzcoz** [comment]
@hoisie I think this PR is ready for initial review to looking forward your suggestion.

**Review by hoisie — APPROVED** [review]

**Comment by hoisie** [comment]
> There is another weird problem: Windows generated dll file is small, about 5~6MB, less than other platforms' file size: about 30MB.

This is very likely a libICU data issue. The libICU data file alone is like 25 MB, which could explain the difference.

I don't think it's urgent to fix this right away. The libICU sqlite integration is only used for `order by ... collate LOCALIZED` and `order by ... collate UNICODE`, which is not super common.

Anyway, I am ok with getting the build working first, and then we can figure out the runtime issues.

**Comment by utzcoz** [comment]
> > There is another weird problem: Windows generated dll file is small, about 5~6MB, less than other platforms' file size: about 30MB.
> 
> This is very likely a libICU data issue. The libICU data file alone is like 25 MB, which could explain the difference.
> 
> I don't think it's urgent to fix this right away. The libICU sqlite integration is only used for `order by ... collate LOCALIZED` and `order by ... collate UNICODE`, which is not super common.
> 
> Anyway, I am ok with getting the build working first, and then we can figure out the runtime issues.

Thanks. I will give more tries for CI's cache for msys2 to reduce CI times, and omit this dll size problem now.

**Comment by utzcoz** [comment]
Looks like we can set `msys2` installation location to define cache directory for `msys2` more easily. I will give a try.

**Comment by utzcoz** [comment]
> Looks like we can set `msys2` installation location to define cache directory for `msys2` more easily. I will give a try.

Oh, it works, and Windows building time reduced to 3min from 20min. There are some clean-up needs to be done. I will clean up those scripts this weekend for final reviewing. :)

**Comment by utzcoz** [comment]
@hoisie I think it can be reviewed again. I have tested it with cache, and Windows cache works fine. The  things to clean up cmake and CI jobs will be left for later PRs, if possible.

**Comment by utzcoz** [comment]
> @hoisie I think it can be reviewed again. I have tested it with cache, and Windows cache works fine. The things to clean up cmake and CI jobs will be left for later PRs, if possible.

Hi @hoisie , could you help to review this PR again? I plan to merge it if there is any important problem should be resolved. Thanks.

**Review by hoisie — APPROVED** [review]

**Comment by utzcoz** [comment]
@hoisie Looks like self-runner encounters problem again.

**Comment by utzcoz** [comment]
https://github.com/robolectric/robolectric/runs/4704128816?check_suite_focus=true instrumentation-tests failed because of network problem to downloading gradle.

**Pull request merged**
