### PR TITLE
Replace Bouncycastle arrays with Java arrays

### PR DESCRIPTION
**Pull request by akhilrm**
### Overview

Replace Bouncycastle arrays with Java arrays
Fixes https://github.com/robolectric/robolectric/issues/7360

### CODE REVIEW

**Comment by utzcoz** [comment]
@akhilrm Please follow https://github.com/robolectric/robolectric/wiki/Robolectric's-code-style to format your code locally and force push again.

**Comment by utzcoz** [comment]
Looks like GitHub Action works again, @akhilrm you can rebase and check format locally, and force-push your branches again if no other problems.

**Review by utzcoz — APPROVED** [review]
LGTM, Thanks.

**Comment by hoisie** [comment]
Thanks!

**Comment by utzcoz** [comment]
@akhilrm Congratulation to your first PR on Robolectric.

**Pull request merged**
