### PR TITLE
Add Detection for Maven/Gradle in RobolectricTestRunner to Replace RobolectricGradleTestRunner

### PR DESCRIPTION
**Pull request by vnayar**
### Overview

Move Maven-specific logic out of AndroidManifest.java and RobolectricTestRunner.java.  Instead, create ManifestFactory which detects whether Maven or Gradel is in use, and returns the appropriate ManifestFactory implementation.  This change should make the use of RobolectricGradleTestRunner unnecessary.

### Other Changes of Note

* Changed pom.xml so tests are run in alphabetical order rather than random.
* Configured the MavenManifestFactory (which contains maven-specific logic pulled from AndroidManifest and RobolectricTestRunner) to strip out config.manifest leading "./".  This is because the manifest is presumed to be relative to the baseDir.

### CODE REVIEW

**Comment by vnayar** [comment]
In this case, I've kept everything in a single commit using "git commit --amend".  Is that the preferred style for Robolectric, or are several separate commits that follow the development preferred?

**Comment by vnayar** [comment]
I presume there are users out there that still use RobolectricGradleTestRunner, so it should not be deleted.  But do you think it would make sense if it were simply an empty extension of RobolectricTestRunner after this change?

**Comment by jongerrish** [comment]
Yes, lets make it empty and mark as @Deprecated we'll remove it after the next release goes out.

**Comment by vnayar** [comment]
What is the preferred workflow for pull requests?  Are merges frowned upon and should I always rebase, delete the old pull request, and make a new one?  Or is it fine to merge in from the mainline?

**Comment by mag** [comment]
I think it's fine to merge master into your branch and trigger a final CI before merging the PR itself.

**Pull request merged**
