### PR TITLE
Regenerate Robolectric test resources

### PR DESCRIPTION
**Pull request by hoisie**
Regenerate Robolectric test resources

This is the result of ./script/build-resources.sh.

These files should NOT be formatted with google-java-format to avoid thrashing.

Also, add android:debuggable="true" flag to the Robolectric test
AndroidManifest.xml to fix tests on the `google` branch.

### CODE REVIEW

**Comment by MGaetan89** [comment]
It seems that the `google` branch still has an old version of the `check_code_style.yml` workflow.
@utzcoz updated it in https://github.com/robolectric/robolectric/pull/9264 to ignore these files.

**Review by MGaetan89 — APPROVED** [review]

**Comment by hoisie** [comment]
Thanks for the review, I am trying to investigate some test failures on the `google` branch:

It looks like there is still a test failing:

```
ShadowPackageManagerTest > applicationFlags FAILED
    expected: 2
    but was : 0
        at org.robolectric.shadows.ShadowPackageManagerTest.applicationFlags(ShadowPackageManagerTest.java:239)
```

**Comment by MGaetan89** [comment]
> Thanks for the review, I am trying to investigate some test failures on the `google` branch:
> 
> It looks like there is still a test failing:
> 
> ```
> ShadowPackageManagerTest > applicationFlags FAILED
>     expected: 2
>     but was : 0
>         at org.robolectric.shadows.ShadowPackageManagerTest.applicationFlags(ShadowPackageManagerTest.java:239)
> ```

You probably reached the same point already, but sharing just in case. It seems that the following returns a different result between the `master` and `google` branches:
https://github.com/robolectric/robolectric/blob/3911f5f9568696ab0dc72544185f089d98b5ae87/shadows/framework/src/main/java/org/robolectric/shadows/ShadowPackageManager.java#L1396

This triggers a call in [`ShadowPackageParser`](https://github.com/robolectric/robolectric/blob/3911f5f9568696ab0dc72544185f089d98b5ae87/shadows/framework/src/main/java/org/robolectric/shadows/ShadowPackageParser.java#L88), but then I don't know where it goes.

**Comment by hoisie** [comment]
Thanks for the info @utzcoz and @MGaetan89 .

Looks like the test started failing in f29bd94f8464114542682dd6822bdb8796962edf.

I will try adding the android:debuggable flag to the application.

**Comment by hoisie** [comment]
@utzcoz sounds good, I will do that on the next bidirectional sync. FYI the only GitHub workflows that are enforced before a CL is merged to Robolectric in Google3 is https://github.com/robolectric/robolectric/blob/master/.github/workflows/copybara_build_and_test.yml and https://github.com/robolectric/robolectric/blob/master/.github/workflows/graphics_tests.yml. The other ones are non-blocking.

**Comment by MGaetan89** [comment]
What about adding the tests one too? https://github.com/robolectric/robolectric/blob/master/.github/workflows/tests.yml

**Pull request merged**
