### PR TITLE
Don't NPE if there's a non-directory with the 'values' prefix

### LINKED ISSUE #3157: NPE in DocumentLoader.loadFile
### Description
Upgraded to new AGP, got this error (stack below).  Tried upgrade Robolectric to 3.4-rc2, still same problem.
  
### Steps to Reproduce
Any test with the RoboletricTestRunner.

### Robolectric & Android Version
Robolectric 3.4-rc2
com.android.tools.build:gradle:3.0.0-alpha3
Kotlin 1.1.2-4
```
  compileSdkVersion 25
  buildToolsVersion "25.0.2"

  defaultConfig {
    minSdkVersion 21
    targetSdkVersion 25
```

### Analysis

The path it's trying to load from is `build/intermediates/res/merged/debug/values-af_values-af.arsc.flat`.  That file exists, but it's not a directory.

```
java.lang.RuntimeException: java.lang.NullPointerException

	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:155)
	at org.robolectric.res.ResourceTableFactory.newResourceTable(ResourceTableFactory.java:43)
	at org.robolectric.res.ResourceMerger.buildResourceTable(ResourceMerger.java:22)
	at org.robolectric.RobolectricTestRunner.getAppResourceTable(RobolectricTestRunner.java:453)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:291)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:35)
	at org.robolectric.res.DocumentLoader.load(DocumentLoader.java:26)
	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:140)
	... 19 more
```

### PR DESCRIPTION
**Pull request by edenman**
Fixes #3157.  Not 100% sure this is the way you want to fix this, but figured it was an easy one to put together.

### CODE REVIEW

**Comment by elye** [comment]
Please consider adding this fix in. I think it would solve my problem having Robolectric in Android Studio 3.0

**Comment by jongerrish** [comment]
Can you rebase onto master please?

**Comment by edenman** [comment]
@jongerrish done

**Comment by tprochazka** [comment]
I think that it should really help. I would just prefer to move `dir.isDirectory()` to the `load()` method, like
```
    for (FsFile dir : files) {
      if (dir.isDirectory) {
         loadFile(dir);
      }
    }
```

Btw. Why loadFile() is called loadFile when it actually don't load file?
It doing something like loadXmlFilesInDirectory(FsFile dir)

**Pull request merged**
