### PR TITLE
Enable in-memory SQLite databases

### PR DESCRIPTION
**Pull request by cesar1000**
### Proposed Changes

SQLite creates an in-memory database when the database path is ":memory:". Twitter runs hundreds of database unit tests, and we have measured speedups of up to 5x in certain server configurations when switching to using in-memory databases.

This patch updates the database file path validation to act as a passthrough for ":memory:". `ContextImpl.openOrCreateDatabase` just calls `getPath()` on this file to pass it into `SQLiteDatabase.openDatabase`.

### CODE REVIEW

**Comment by hidroh** [comment]
@cesar1000 does it have any implications on memory when you switch to in-memory DB, e.g. test machine requires much more memory than before?

**Comment by cesar1000** [comment]
@hidroh not that I have observed. Our test databases are generally fairly small, so memory needs are minimal. Also, I didn't notice any difference in behavior, other than the test speedup. We also use the following settings in our tests:

```
// Speed up tests by disabling safe writing to disk.
database.execSQL("PRAGMA synchronous = off;");
// Disable transactions. As a result, rollback does not work.
database.execSQL("PRAGMA journal_mode = off;");
// Disable file locking.
database.execSQL("PRAGMA locking_mode = exclusive;");
```

**Comment by karlicoss** [comment]
@cesar1000 wow, these pragma tricks are interesting. Slightly offtopic, but do you guys have some talks or blog posts on techniques you use for Twitter app testing?

**Comment by cesar1000** [comment]
@karlicoss yeah, they just disable features that are not particularly useful when running tests. They don't make much of a difference with in-memory databases though.

We haven't published any public information about testing on Android, but I'd like to do something soon!

**Comment by jongerrish** [comment]
Can you merge this?

**Comment by cesar1000** [comment]
Yeah, done.

**Comment by jongerrish** [comment]
Again, sorry.

**Comment by cesar1000** [comment]
Done.

**Pull request merged**
