### PR TITLE
Update to using latest version of Guava.

### PR DESCRIPTION
**Pull request by charlesmunger**

### CODE REVIEW

**Comment by erd** [comment]
We used to use Guava heavily, but removed it because it was causing version conflicts with downstream users. We should remove it from the few places that are remaining.

**Comment by charlesmunger** [comment]
Does that mean that robolectric can't have any third party dependencies, because they could conflict with code under test? Can we jarjar guava to make it acceptable?

There's lots of utilities that guava provides to make things nicer, but there's also packages that would be hard to live without - in particular, my fixes for serializing execution of ordered broadcasts would have been much more complex and error-prone without ListenableFuture.

**Comment by erd** [comment]
Let me see if I can dig up the old issue for context.

**Comment by jongerrish** [comment]
@erd I merged this because it gets us into a good state and if we're going to depend on Guava (at least in the short term) we should be on the latest version, as there will be version skew at any arbitrary version. Lets chat more about whether we should avoid Guava or not though.

**Pull request merged**
