### PR TITLE
Restructure androidx_test with sharedTest pattern

### PR DESCRIPTION
**Pull request by utzcoz**
Fix https://github.com/robolectric/robolectric/issues/6885.

### CODE REVIEW

**Comment by utzcoz** [comment]
There are two problems of this PR:

1. Is `AndroidManifest-NoTestPackageActivityies.xml` useful?
2. `ActivityScenarioTest` has three failed tests when running on Emulator. They are both related to `onWindowFocusChanged` lifecycle callback sequence. I need to check AOSP source code to check the real behavior of `onWindowFocusChanged`.

**Comment by utzcoz** [comment]
It's interesting that there is different failed reason for those tests when running tests on SDK 28 Emulator(above results are generated on SDK 30 Emulator):

```
launch_callbackSequence

missing (1): onWindowFocusChanged true
---
expected   : [onCreate, onStart, onPostCreate, onResume, onWindowFocusChanged true]
but was    : [onCreate, onStart, onPostCreate, onResume]
	at org.robolectric.integrationtests.axt.ActivityScenarioTest.launch_callbackSequence(ActivityScenarioTest.java:107)

launch_pauseAndResume_callbackSequence

unexpected (2): onWindowFocusChanged false, onWindowFocusChanged true
---
expected      : [onCreate, onStart, onPostCreate, onResume, onWindowFocusChanged true, onPause, onResume]
but was       : [onCreate, onStart, onPostCreate, onResume, onWindowFocusChanged true, onPause, onWindowFocusChanged false, onResume, onWindowFocusChanged true]
	at org.robolectric.integrationtests.axt.ActivityScenarioTest.launch_pauseAndResume_callbackSequence(ActivityScenarioTest.java:119)

launch_stopAndResume_callbackSequence

unexpected (2): onWindowFocusChanged false, onWindowFocusChanged true
---
expected      : [onCreate, onStart, onPostCreate, onResume, onWindowFocusChanged true, onPause, onStop, onRestart, onStart, onResume]
but was       : [onCreate, onStart, onPostCreate, onResume, onWindowFocusChanged true, onPause, onWindowFocusChanged false, onStop, onRestart, onStart, onResume, onWindowFocusChanged true]
	at org.robolectric.integrationtests.axt.ActivityScenarioTest.launch_stopAndResume_callbackSequence(ActivityScenarioTest.java:132)


```

**Comment by utzcoz** [comment]
I re-run those tests on Emulator with SDK 30 locally, `ActivityScenarioTest#launch_callbackSequence` passed. Looks like those tests are flaky-tests.

**Comment by utzcoz** [comment]
> I re-run those tests on Emulator with SDK 30 locally, `ActivityScenarioTest#launch_callbackSequence` passed. Looks like those tests are flaky-tests.

Robolectric only have two places that call `onWindowFocusChanged`:

1. [`ActivityController#recreate`](https://github.com/robolectric/robolectric/blob/b2a2f1dc2b79a8fef8b29495252c8b633b664682/shadows/framework/src/main/java/org/robolectric/android/controller/ActivityController.java#L531).
2. [`RoboMonitoringInstrumentation#startActivitySyncInternal`](https://github.com/robolectric/robolectric/blob/589f03e46b5d7a7ef39ac3fdcaf777461ed64fad/robolectric/src/main/java/org/robolectric/android/internal/RoboMonitoringInstrumentation.java#L111).

Looks like above mentioned tests are written with Robolectric result, but they don't  meet the real behavior of real Emulator, window focus also changed after `onResume` and `onPause`. There is one thing needs to be pointed out: from Android Q, window focus state is not bound with `onResume`, because AOSP supports multi-resumed state for multi-window, and there will be multiple resumed window, but only one window has focus.

**Comment by utzcoz** [comment]
[`InstrumentationActivityInvoker#pauseActivity` will start `EmptyFloatingActivity` to trigger test Activity's pause state](https://cs.android.com/androidx/android-test/+/master:core/java/androidx/test/core/app/InstrumentationActivityInvoker.java;l=454-485?q=startFloatingEmptyActivitySync&ss=androidx), and `EmptyFloatingActivity` will gain window focus, and test Activity will lost window focus. But what about `EmptyFloatingActivity` is not focusable? Will test Activity lost window focus too? I will write demo to verify this behavior.

**Comment by utzcoz** [comment]
Looks like the problem of  window focused callback difference between Robolectric and Emulator/real device needs more time to find the approach to fix. I decide to keep them at test directory, and fire a new issue for them.

**Comment by utzcoz** [comment]
I will wait next stable/beta AndroidX test release and bump all AndroidX test dependencies to latest.

**Comment by utzcoz** [comment]
Hi @hoisie , @brettchabot , I think this PR is ready for reviewing now. Could you help to review it? Thanks.

**Review by hoisie — APPROVED** [review]

**Comment by utzcoz** [comment]
Hi @hoisie @brettchabot , it's my another attempt to try to checkin this PR. Could you help to review this PR again? Thanks.

**Review by hoisie — APPROVED** [review]
Thanks!!

**Pull request merged**
