### PR TITLE
[EXPERIMENTAL] Real rendering of layouts

### PR DESCRIPTION
**Pull request by xian**
Based on #1962.

Rebase of https://github.com/zhongyu05/robolectric.git master -- was af8160572.

### CODE REVIEW

**Comment by ming13** [comment]
@xian, terribly sorry to ask you this — can you please rebase it once again? I wanted to take a look how it works in real life on the recent SDK and Robolectric versions. There is not a lot of documentation on `layoutlib` around and this PR seems to be the best sample on the internet (besides Android Studio sources I guess).

**Comment by nikwotton** [comment]
@xian Looking through this PR, am I correct in reading that this allows taking screenshots of tests run through robolectric? And if so, is there any plan to ever revive this or something like it to be merged into master?

**Comment by xian** [comment]
This PR is outdated; created #4804 to track progress on this effort.

**Comment by nikwotton** [comment]
💯

**Pull request closed without merging**
