### PR TITLE
Add ShadowScrollView#scrollTo

### PR DESCRIPTION
**Pull request by utzcoz**
Close https://github.com/robolectric/robolectric/issues/6176

### CODE REVIEW

**Comment by utzcoz** [comment]
@hoisie it is a reopen PR for `ShadowScrollView#scrollTo`.

**Comment by utzcoz** [comment]
Hi @hoisie , I rebase it to current master, and it is ready for review.

**Comment by utzcoz** [comment]
Hi @hoisie , I rebased it on the current master branch, and I want to see whether there is a change to merge it. Thanks.

**Comment by hoisie** [comment]
Thanks, I'll take a closer look at this. I don't have a great understanding of ShadowScrollView at the moment so I may need some time to review .

**Comment by hoisie** [comment]
This should have a childCount > 0 check:

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/widget/ScrollView.java;l=1780?q=scrollview

**Comment by utzcoz** [comment]
> This should have a childCount > 0 check:
> 
> https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/widget/ScrollView.java;l=1780?q=scrollview

Thanks. I am considering whether to add child scroll position checking.

**Comment by utzcoz** [comment]
> > This should have a childCount > 0 check:
> > https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/widget/ScrollView.java;l=1780?q=scrollview
> 
> Thanks. I am considering whether to add child scroll position checking.

Hi @hoisie , the new commit adds child count checking for it. But it maybe break current tests of `ShadowScrollView` related to scroll. I have fixed tests of `ShadowScrollViewTest`, but it maybe be risk for existed tests of other projects.

**Comment by hoisie** [comment]
Looking at this now.

**Comment by hoisie** [comment]
I am a little confused about the example in https://github.com/reid-mcpherson/ScrollToCoordsBug 

Is there anything to scroll in the Scroll View of https://github.com/reid-mcpherson/ScrollToCoordsBug/blob/master/app/src/main/res/layout/activity_main.xml?

Are we sure that Robolectric is not doing the right thing there?

**Comment by utzcoz** [comment]
> I am a little confused about the example in https://github.com/reid-mcpherson/ScrollToCoordsBug 
> 
> Is there anything to scroll in the Scroll View of https://github.com/reid-mcpherson/ScrollToCoordsBug/blob/master/app/src/main/res/layout/activity_main.xml?
> 
> Are we sure that Robolectric is not doing the right thing there?
> 

I can provide one occasion I have met, https://github.com/farmerbb/Taskbar/blob/2767c59569b1b97d6858ba22184eb39fee380fdf/app/src/main/java/com/farmerbb/taskbar/ui/TaskbarController.java#L1114-L1126 . It uses 'scrollTo'  to scroll view, and I use custom shadow to fix it https://github.com/farmerbb/Taskbar/blob/db983e405f8d77ab39d91c6d8c3ff1b6fdbc374f/app/src/test/java/com/farmerbb/taskbar/shadow/TaskbarShadowScrollView.kt.

**Comment by utzcoz** [comment]
Maybe can be fixed by https://github.com/robolectric/robolectric/pull/7371.

**Pull request closed without merging**
