### PR TITLE
[utils module] [Test conversion] Pref stats collector test

### PR DESCRIPTION
**Pull request by hellosagar**
### Overview
Converted the [PerfStatsCollectorTest](https://github.com/hellosagar/robolectric/blob/6b3bc9ce48fbecf9c09af88a9a80e29a9f4c2c65/utils/src/test/java/org/robolectric/util/PerfStatsCollectorTest.kt)  from java to kotlin

### Proposed Changes
In this, I've basically removed the java version `PerfStatsCollectorTest` and add the kotlin version

### CODE REVIEW

**Review by hoisie — APPROVED** [review]

**Comment by utzcoz** [comment]
@hellosagar Maybe we don't need commit to add Kotlin support util modules, because it has been merged into previous PR.

**Comment by hellosagar** [comment]
Yeah you are right, lme drop that one

**Comment by hellosagar** [comment]
@utzcoz From now on, for problems like this 
I will create a branch from the master named `Convert Class A` for class A and then for the same module of class B, I will create a branch from `Convert Class A` instead of master. 

or 

should I add the commit about adding the kotlin support in only one branch and then other branches will only contains the commit about conversions only

**Comment by utzcoz** [comment]
I recommend to create different branches for different PRs.

**Comment by hellosagar** [comment]
Yeah, that's right, Imm talking about the approach, I mean should I create the branch from master or form the derived branch to create the PR for a problem like this where one commits is going to be in differents PR for example like adding the kotlin support

**Comment by utzcoz** [comment]
> Yeah, that's right, Imm talking about the approach, I mean should I create the branch from master or form the derived branch to create the PR for a problem like this where one commits is going to be in differents PR for example like adding the kotlin support

You can create branch from derived branch, and rebase it on latest master when previous derived branches all merged.

**Comment by hellosagar** [comment]
ded, Ive merged accidently

**Comment by hellosagar** [comment]
Now, it looks okay

**Review by utzcoz — APPROVED** [review]

**Pull request merged**
