### PR TITLE
[test conversion] [resource module] ActivityDataTest

### PR DESCRIPTION
**Pull request by hellosagar**
### Overview
Converted the [ActivityDataTest](https://github.com/hellosagar/robolectric/blob/5a6dccbf32480b7d87639a1b0f64aeddf6fa3453/resources/src/test/java/org/robolectric/manifest/ActivityDataTest.kt) from java to kotlin.

### Proposed Changes
In this, I've basically removed the java version `ActivityDataTest` and added the kotlin version.

### CODE REVIEW

**Review by utzcoz — APPROVED** [review]

**Comment by utzcoz** [comment]
@hellosagar Why doesn't this module need kotlin dependency?

**Review by utzcoz — CHANGES_REQUESTED** [review]
Maybe we need to add spotless for this module to validate Kotlin format on CI.

**Comment by hellosagar** [comment]
> Maybe we need to add spotless for this module to validate Kotlin format on CI.

oops, yes you are right. lme add that

**Comment by hellosagar** [comment]
Life is so easy when we have Ubuntu to develop stuff 😌

**Review by utzcoz — APPROVED** [review]

**Comment by utzcoz** [comment]
Hi @hoisie could you help to validate it internal? Thanks.

**Comment by hellosagar** [comment]
This PR contains the spotless plugin for the Gradle file, so I didn't add it in other PRs of `resource` module, lets first this first and then rest of `resource` modules PRs

**Comment by hellosagar** [comment]
Same goes for this, Once, this is merged, I'll make the other PRs of the `resource` module to be review ready

**Comment by utzcoz** [comment]
Hi @hellosagar @hoisie I want to continue this module's test code Kotlin conversion after I have fixed some compatibility problems of Robolectric with Kotlin 1.7.10. @hellosagar Could you rebase this PR and check what I did in `utils/build.gradle` about Kotlin to make tests passed? Thanks.

**Review by utzcoz — CHANGES_REQUESTED** [review]
Need to rebase to latest master branch and add more Gradle config for Kotlin.

**Comment by utzcoz** [comment]
This PR will be processed by https://github.com/robolectric/robolectric/pull/7934.

**Pull request closed without merging**
