### PR TITLE
Upgraded Support and Multidex Library versions to v23

### PR DESCRIPTION
**Pull request by diegotori**
Seeing that its now building against Marshmallow, "shadows-support-v4" and "shadows-multidex" should be likewise brought in line. That way, it can eventually support the new ContextCompat permission utility methods.

So far, after upgrading their version numbers in both the "install-dependencies" script and in their POMs, it did not fail any of the existing test cases.  

Also, I kept the previous versions as trailing ones in order to keep other non-upgraded modules building (i.e. "shadows-play-services").

### CODE REVIEW

**Comment by jongerrish** [comment]
Can you rebase? I think you can maps jar.

**Comment by jongerrish** [comment]
Can you also update the text from "Android Repository" to "Android Support Repository" which is the item in the android tool.

**Comment by diegotori** [comment]
Updated name to "Android Support Repository."

**Comment by diegotori** [comment]
When you mean "you can maps jar," does that mean to say that I can essentially install the Google Maps jar for v23 Marshmallow?

**Comment by diegotori** [comment]
Had to revert the Google Maps v23 JAR upgrade since TravisCI isn't fetching "addon-google_apis-google-23" from the SDK Manager. Is that something that should be upgraded as a result of the library supporting v23?

**Comment by jongerrish** [comment]
I just meant bumping 

MAPS_API_VERSION = "18" -> "23"
MAPS_REVISION_VERSION = "4" -> "1"

This was working for me, but I'll accept this PR as is  - thanks for the contribution :-)

**Comment by diegotori** [comment]
If that was the case, then I can make a separate PR for that one, provided that TravisCI fetches that version of Google Maps JAR. I clearly remember it was passing when I ran it on my dev environment due to the fact that I had that latest version installed.

**Pull request merged**
