### PR TITLE
Changed the tests from java to kotlin for utils module

### PR DESCRIPTION
**Pull request by hellosagar**
### Overview
I've converted the test cases from `java` to `Kotlin` for the `utils` module.

### Proposed Changes
For this, I've added the Kotlin Gradle plugin dependency to the `parent` build.gradle and a specific Kotlin plugin to the `utils` module build.gradle. 

### Thing I've doubt about
During the [discussion](https://github.com/robolectric/robolectric/discussions/7127#discussioncomment-2346565) its mentioned there that for kotlin code style robolectric uses `Spotless` + `ktmft` + `Google style to format Kotlin` I found out that

**Spotless**: It's a way to format the Kotlin code it has a [IntelliJ plugin](https://plugins.jetbrains.com/plugin/18321-spotless-gradle) to format easily and with their plugin, with one click I can format the code easily.

**Ktfmt**: It also reformats Kotlin source code to comply with the common community standard for Kotlin code and it also comes with the IntelliJ plugin with one click I can reformat the code.

**Google-style to format Kotlin**: It is basically a google standard on how to format the code.

Currently, all three are enabled in the Android Studio, and why we are using all three. Cant, we use one of them for example Ktfmt?

### Issue
 - Currently, 2 test cases are still failing which I'm unable to fix it so far because of a lack of code understandability.
Screenshot 2022-04-09 at 8 40 34 PM

 - Another issue IDK how it works but when I put the two interfaces `Thing` and `Umm` separate in their own file test cases are passed but if I make them as a nested interface in `InjectorTest` tests are failing, I think its related visibility issue but the reason I don't exactly.

### CODE REVIEW

**Comment by utzcoz** [comment]
I think ktfmt is what I have said the "Google code style for Kotlin". And Spotless is a front end that supports multiple format tools or styles and we can use it with config to enable specific format tool for Kotlin Java or gradle script. We use spotless to levarage ktfmt tool to format kotlin code for Robolectric to meet Google code style requirement for kotlin code. @hoisie could you help to explain what we choose ktfmt? Thanks.

**Comment by utzcoz** [comment]
And could you split this PR to multiple PRs to ensure each one is small? Current PR is hard to compare before converting and after.

**Comment by hellosagar** [comment]
> I think ktfmt is what I have said the "Google code style for Kotlin". And Spotless is a front end that supports multiple format tools or styles and we can use it with config to enable specific format tool for Kotlin Java or gradle script. We use spotless to levarage ktfmt tool to format kotlin code for Robolectric to meet Google code style requirement for kotlin code. @hoisie could you help to explain what we choose ktfmt? Thanks.

I see got that `ktfmt` is actually using the google standards to format the code and basically but where in robolectric where `Spotless` is using inaction still I I'm little confused about this

**Comment by hellosagar** [comment]
> And could you split this PR to multiple PRs to ensure each one is small? Current PR is hard to compare before converting and after.

ooops my bad sure, from now I will try to keep the PR short of about 100 - 200 lines of changes

**Comment by utzcoz** [comment]
> where in robolectric where Spotless is using inaction still I I'm little confused about this

I don't know what do you mean. IMO, how Robolectric uses spotless is very clear, and it follows spotless tutorial to add it and check it on CI.

**Comment by hellosagar** [comment]
> > where in robolectric where Spotless is using inaction still I I'm little confused about this
> 
> I don't know what do you mean. IMO, how Robolectric uses spotless is very clear, and it follows spotless tutorial to add it and check it on CI.

ah okay, lme read more about it

**Comment by utzcoz** [comment]
@hellosagar You can check https://github.com/robolectric/robolectric/pull/7125 for how Robolectric uses spotless.

**Pull request closed without merging**
