### PR TITLE
Fixes 1986

### LINKED ISSUE #1986: SQLite error when running tests
Hello, I have troubles running my tests suite on Ubuntu (everything is running fine on my OSX environment). 

When i execute my full tests suites, the first tests are doing good, but they start to randomly crash with the following error (see below). 

Any hint on where this could come from ? Why is it happening only on Ubuntu and not on OSX ?

Thanks

Robolectric 3.0
Shadow support v4 3.0
Gradle Wrapper 2.6
android-gradle 1.3.0

```
java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError: DB[46] will not dispose from a non-confining thread
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:244)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at   org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
    at sun.reflect.GeneratedMethodAccessor158.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
    at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError: DB[46] will not dispose from a non-confining thread
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:477)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections.close(ShadowSQLiteConnection.java:390)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections.reset(ShadowSQLiteConnection.java:402)
    at org.robolectric.shadows.ShadowSQLiteConnection.reset(ShadowSQLiteConnection.java:80)
    at org.robolectric.Shadows.reset(Shadows.java:1626)
    at org.robolectric.Robolectric.reset(Robolectric.java:22)
    at org.robolectric.internal.ParallelUniverse.resetStaticState(ParallelUniverse.java:43)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:233)
    ... 33 more
Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: DB[46] will not dispose from a non-confining thread
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:462)
    ... 40 more
Caused by: java.lang.AssertionError: DB[46] will not dispose from a non-confining thread
    at com.almworks.sqlite4java.Internal.recoverableError(Internal.java:46)
    at com.almworks.sqlite4java.SQLiteConnection.dispose(SQLiteConnection.java:363)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections$3.call(ShadowSQLiteConnection.java:394)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:452)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:446)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
```

### PR DESCRIPTION
**Pull request by matthewhubblerose**
Fixes #1986

### Overview

When running tests on Linux platforms, occasionally tests would fail due to an exception like the following:
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError: DB[46] will not dispose from a non-confining thread
```

The `AssertionError` is thrown from the sqlite4java library when an attempt was made to close a connection on a different thread to the one it was opened on. All interaction with connections and statements are done by submitting `Callable`s to the `dbExecutor` `ExecutorService`, which is a single thread executor.

I believe the issue occurs as there is a race condition in the reset function, which used to look like this:
```
public void reset() {
  for (long connectionPtr : connectionsMap.keySet()) {
    close(connectionPtr);
  }
  dbExecutor.shutdown();
  try {
    dbExecutor.awaitTermination(30, TimeUnit.SECONDS);
  } catch (InterruptedException e) {
    throw new RuntimeException(e);
  }
  dbExecutor = Executors.newSingleThreadExecutor();
  connectionsMap.clear();
  statementsMap.clear();
}
```

 If a connection was opened between the last call to `close(connectionPtr)` and this line: `dbExecutor = Executors.newSingleThreadExecutor()`, then a connection would have been opened on the old thread, and any attempt to close it would be on a new thread.

### Proposed Changes

The fix is to synchronize all access to anything that interacts with `dbExecutor`, `connectionsMap` and `statementsMap`. A key implication of this is that any work submitted to the dbExecutor must not try to synchronize on the lock, as it will cause a deadlock.

As well as this `useInMemoryDatabase ` has been made an `AtomicBoolean` as it was written to on multiple thread and read on the `dbExecutor` thread. Also when connections are closed they now get removed from `connectionsMap`

### CODE REVIEW

**Comment by matthewhubblerose** [comment]
I've managed to run the tests on my machine, but I've been unable to use a locally built snapshot version to test with on my project. This **should not** be merged until it's been tested with some projects.

Is anyone able to provide some instructions on getting a snapshot version built that can be included from a project. Including the snapshot version I built locally results in this gradle error:

```
Error:

Could not find org.robolectric:framework:3.4-SNAPSHOT.
Required by:
    project :myproject > org.robolectric:robolectric:3.4-SNAPSHOT
```

**Comment by hoisie** [comment]
@matthewhubblerose does running `./gradlew install` from the root Robolectric directory and adding `mavenLocal()` to your repositories section in your build.gradle not work? After that you should be able to use 3.4-SNAPSHOT.

**Comment by hoisie** [comment]
You're right, running `./gradlew install` does not generate the correct artifact id for `shadows/framework` (previously shadows/shadows-core). Can you try applying #3212 locally and re-running `./gradlew install`?

**Comment by jongerrish** [comment]
Merged, so you can just sync to head now

**Comment by matthewhubblerose** [comment]
@hoisie @jongerrish Thanks, after syncing I've managed to test these changes on my project.

Before this change, 1 in 3 of our builds in linux would fail due to test failures caused by:
```
java.lang.AssertionError: DB[46] will not dispose from a non-confining thread
```

I've now run 10 builds on each platform and not had any failures, each build running several thousand tests. I'm happy with the testing performed for this change, let me know if any other verification is required.

**Comment by matthewhubblerose** [comment]
Do I need to get in contact with someone for a review? I have verified this change fixes 1986 so it would be good to get it merged.

**Comment by jongerrish** [comment]
@matthewhubblerose We'll try and merge this tomorrow am, need verify it doesn't break any internal tests first, but this looks awesome, this issue has caused us a few flaky failures also.

**Comment by matthewhubblerose** [comment]
@jongerrish Good to hear, hopefully the test run goes well.

Do you know what the "sheepfood" build is that has failed? It seems to have failed on many pull requests, I think it's a recent addition.

**Comment by jongerrish** [comment]
It's an internal selection of our test corpus we run to get a feel of the
stability of the change which can show up other considerations or
conditions the author failed to test. In those cases we'll ask the author
to add tests to fix those conditions. In other cases it could be flaky or
badly written internal tests. I'll take a look when I get in this morning.

**Comment by matthewhubblerose** [comment]
@jongerrish Did you get a chance to take a look at the test results? Apologies if the timing of my messages isn't great, the time zone for London isn't very compatible with the US 😄

**Comment by xian** [comment]
Thanks @matthewhubblerose!

**Comment by kenyee** [comment]
when is the next 3.4 RC with this fix?

**Pull request merged**
