### PR TITLE
Increased AsyncTask realism

### PR DESCRIPTION
**Pull request by kriegfrj**
This strips back the shadow implementation to minimize the use of shadow code and maximize the use of real Android code. Aside from the usual benefits of code reuse and streamlining, the following specific improvements have been made:
* The previous implementation would wrap `doInBackground()` in a runnable which posted to the background thread scheduler. This post would happen on the background thread, but the problem was that this didn't guarantee that the real runnable would later be invoked on the background - it depended on which thread the background scheduler was advanced/flushed. This has been fixed - background task execution is now properly run on the executor’s thread. This fixes point 5.1 of issue #1879.
* In spite of the above, execution is still synchronized through the standard schedulers so that the tests should still be backwards compatible with the present usage patterns of the foreground and background schedulers. 
* There were some inconsistencies with the old shadow implementation with regard to when certain state changes occur during task execution, as compared with the real Android behaviour (I put this down to incomplete/ambiguous documentation for ``AsyncTask``). In particular:
 * `isCancelled()` will always return `true` after a call to `cancel()`, even if the call to `cancel()` failed.
 * The previous shadow behaviour would transition to the `FINISHED` state before `onPostExecute()` or `onCancelled()`, whereas real ANDROID doesn't set to `FINISHED` until after.

I altered the tests to adjust  for the real Android differences and added a couple more tests to cover some cases that weren’t covered. In short, it now more accurately emulates what happens in real Android.

### CODE REVIEW

**Comment by kriegfrj** [comment]
I've had a bit of a look at these failures, and unfortunately it doesn't seem to fail very consistently on my machine which will make it difficult to debug. Will hopefully have a patch soon.

**Comment by erd** [comment]
Are these changes dependent on enabling the global scheduler? Or will they work with the old behavior? `AsyncTaskLoader` uses an `AsyncTask` to perform the loading - does it need similar changes to take advantage of the new scheduling behavior?

**Comment by kriegfrj** [comment]
* Changes should work with or without global scheduling. All of the tests (which are based on the preexisting tests) use dual foreground/background schedulers. Unfortunately due to the way I wrote it isn't possible to switch between global and multiple within a single test run, so it isn't possible to write test cases for both.

**Comment by jaredsburrows** [comment]
@kriegfrj Rebase your branch with master.

**Comment by kriegfrj** [comment]
Please don't merge this branch just yet. I think I have traced down another potential race condition which might cause intermittent issues (and may be the source of the apparent discrepancies between Travis' results and the results on my own machine.

**Comment by kriegfrj** [comment]
Sorry I've had limited time to work on this in recent days, but I have managed to rule out the race condition i thought it was and discovered instead that these failures seem to have something to do with the test execution order. Hopefully I'll have this sorted out soon. It would be useful if the surefire random execution order could be reseeded with a seed from a previous run so that I could reliably reproduce a failing execution order.

**Comment by kriegfrj** [comment]
I think I have fixed the intermittency issues. The problem seemed to be that I fixed one (by spin-waiting at the end of the test) while simultaneously introducing another (by removing the pre-call to `resetStaticState()`).

There is still a (minor) issue in that the resetter does not reset the default `Executor`, but this cannot be implemented at the moment due to the issues that arise when `resetStaticState()` is called - in a nutshell, it causes the VM to initialize the `AsyncTask` class, which in turn causes it to try and access the main looper, which (on the first run at least) has not had prepareMainLooper() called. I will try and raise a separate issue for this.

**Pull request merged**
