### PR TITLE
Bump apiCompatVersion to 4.7

### PR DESCRIPTION
**Pull request by utzcoz**
It is used for next replease to compare API changes with command:

```
./gradlew :robolectric:checkForApiChanges
```

### CODE REVIEW

**Comment by utzcoz** [comment]
I noticed a bug of `checkForApiChanges` with a wrong from dependency. Looks like `checkForApiChanges` is a great tool to generate API changes for new release.

**Review by hoisie — COMMENTED** [review]
As far as I know this should be something like `4.7`. I believe it only gets bumped when API signatures change on a way that  causes build breaks.

To be honest I don't quite understand what the expectations of this version is. Maybe to catch regressions when someone changes API signatures?

**Comment by utzcoz** [comment]
This version is used at https://github.com/robolectric/robolectric/blob/master/robolectric/build.gradle#L72-L81.  `CheckApiChangesPlugin.groovy` will use it as "from" release, and calculate API changes between it and current source code. I don't whether there is an old release version that show API changes for developers. API changes includes removed/added/changed.

**Comment by utzcoz** [comment]
https://github.com/robolectric/robolectric/releases/tag/robolectric-4.0 is an example to show API changes at release note.

**Review by hoisie — APPROVED** [review]

**Comment by utzcoz** [comment]
I will file a new issue for the problem of `checkForApiChanges` I found this weekend.

**Pull request merged**
