### PR TITLE
Enable integration_tests:sparsearray tests

### PR DESCRIPTION
**Pull request by utzcoz**
After included, Android Studio will mark directories for source code correctly.

### CODE REVIEW

**Comment by utzcoz** [comment]
Oh, it also fixes "sparsearray" not found when executing `./gradlew :integration_tests:sparsearray:test`.

**Comment by utzcoz** [comment]
Oh, looks like `./gradlew :integration_tests:sparsearray:test` don't run `SparseArrayTest`. I will update this PR to try to fix it.

**Comment by utzcoz** [comment]
> Oh, looks like `./gradlew :integration_tests:sparsearray:test` don't run `SparseArrayTest`. I will update this PR to try to fix it.

After enabling those tests, looks like they can't find `set` method when running tests under 31.

**Comment by hoisie** [comment]
cc @JuliaSullivanGoogle 

I believe as-is the `integration_tests:sparsearray` test will fail, because Robolectric is always configured to use the preinstrumented jars, and because the sparsearray.set support is a change in the instrumentation, it won't be used.

@JuliaSullivanGoogle is working on a change that adds a system property to disable preinstrumented jars, which will be used in the GitHub CI. It might slow things down a small amount, but not significantly. When we do another release and release a new set of preinstrumented jars, we can switch back to using them in GitHub CI.

**Comment by utzcoz** [comment]
> because the sparsearray.set support is a change in the instrumentation, it won't be used.

Oh, I forget preinstrumented jar. I actually failed on my local machine, and I just push related commit to this PR for testing and reviewing.

> @JuliaSullivanGoogle is working on a change that adds a system property to disable preinstrumented jars, which will be used in the GitHub CI.

That's cool. It's very useful for GitHub CI and local testing/debugging. I will keep this PR to draft state, and wait @JuliaSullivanGoogle 's system property to disable preinstrumented jar.

**Comment by utzcoz** [comment]
I will rebase and check it again, today.

**Comment by utzcoz** [comment]
Very strange that some tests are skipped:

```
org.robolectric.integrationtests.sparsearray.SparseArraySetTest > testSparseArrayBracketOperator_callsSetMethodPreApi31[29] SKIPPED

org.robolectric.integrationtests.sparsearray.SparseArraySetTest > testSparseArrayBracketOperator_callsSetMethodPreApi31[30] SKIPPED

org.robolectric.integrationtests.sparsearray.SparseArraySetTest > testSparseArrayBracketOperator_callsSetMethodPreApi31 SKIPPED

org.robolectric.integrationtests.sparsearray.SparseArraySetTest > testSparseArraySetFunction_callsSetMethodPreApi31[29] SKIPPED

org.robolectric.integrationtests.sparsearray.SparseArraySetTest > testSparseArraySetFunction_callsSetMethodPreApi31[30] SKIPPED

org.robolectric.integrationtests.sparsearray.SparseArraySetTest > testSparseArraySetFunction_callsSetMethodPreApi31 SKIPPED
```

**Comment by utzcoz** [comment]
Okay, I found the reason: the current config uses legacy resource, and it is not supported after P with thrown exception from `SandboxTestRunner#getSandbox`, and tests targeted to those newer APIs will be skipped. We should update `build.gradle` to normal app template with `includeAndroidResource` enabled.

**Comment by utzcoz** [comment]
> Okay, I found the reason: the current config uses legacy resource, and it is not supported after P with thrown exception from `SandboxTestRunner#getSandbox`, and tests targeted to those newer APIs will be skipped. We should update `build.gradle` to normal app template with `includeAndroidResource` enabled.

Fixed by transferring to use Robolectric's Android module plugin to enable `includeAndroidResource`. When I trying to use `robolectric.usePreinstrumentedJars` locally, I found I should execute `./gradlew clean` before running `./gradlew :integration_tests:sparsearray:test -Drobolectric.usePreinstrumentedJars=false`. I also want to add it to `sparsearray`'s `build.gradle`, but it doesn't work correctly with can't find `android-all` dependency error, although I execute `./gradlew clean` firstly. I have confirmed that I have installed normal `android-all` locally. @JuliaSullivanGoogle do you have encountered similar problem maybe caused by cache?

**Comment by utzcoz** [comment]
It's strange: `actions/checkout` doesn't clone Robolectric with recursive although I have added config for it. The output shows that it force `no-recursive-module`: `  /usr/local/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +cdefd9fce1399da7cfdff61a384a38233b9f2072:refs/remotes/pull/7006/merge`.

**Comment by utzcoz** [comment]
Looks like this PR triggers ICU building for instrumentation-tests on Emulator, and it failed with some reasons.

**Comment by utzcoz** [comment]
```
ERROR:D8: Cannot fit requested classes in a single dex file (# methods: 69779 > 65536)
```
multidex error raised for sparsearray.

**Comment by utzcoz** [comment]
The `api project(":robolectric")` adds `nativeruntime` to `sparsearray` module, and it triggers building for ICU. This PR also reduce full `robolectric` dependency with `shadowapi` only. I think it can be review again @hoisie @JuliaSullivanGoogle .

BTW, will i4 version of preinstrumented jars published recent days?

**Comment by hoisie** [comment]
@utzcoz made https://github.com/robolectric/robolectric/pull/7156 to bump preinstrumented jars version

**Comment by hoisie** [comment]
@utzcoz preinstrumented jars a bumped, also 4.8-alpha-1 is released, so this should be unblocked?

**Review by hoisie — APPROVED** [review]

**Comment by utzcoz** [comment]
> @utzcoz preinstrumented jars got bumped, also 4.8-alpha-1 is released, so this should be unblocked?

Yup. I will rebase and rerun checking today.

**Pull request merged**
