### PR TITLE
Issue #1212 : minimal handling of domains and subdomains in cookies

### PR DESCRIPTION
**Pull request by stephanenicolas**
This should solve : 
https://github.com/robolectric/robolectric/issues/1212

It has been rebased on current master, and comments of previous PR have been adressed : 
https://github.com/robolectric/robolectric/pull/1296.

(there is one comment about using "system time" that didn't make sense to us and we had no follow up on that.

@erd Any chance to get that in for next RC ?

---- 
I can confirm that the present PR fixes the issue.
Btw, it's not been very easy to build Robolectric, is there any document that explains how to do it ?

### CODE REVIEW

**Comment by erd** [comment]
> Any chance to get that in for next RC ?

I'm planning on pushing another RC this weekend, so I'll make sure to get this in.

**Comment by stephanenicolas** [comment]
@erd thx for planning to merge this soon. It would be great for this week end.

For the instructions : 
* how to deal with profiles in the build 
* also, it looks really difficult to fork Robolectric now : the shadow core classes that are built against different versions of android classes are looked for dynamically by maven, and maven looks in a given set of repos (central, etc.). So when forking, it is very difficult to get a usable fork as the fork's artifacts are not retrieved by maven. Is there any thing we could do to make this easier ? Maybe the instructions should explain how to set up a custom local repo for these dependencies to be retrieved.

**Comment by erd** [comment]
I manually merged this in 3c4ed0c1e7bcd13a93e1bd5212e46f6557047169 but typoed the commit message.

**Comment by erd** [comment]
Thanks for the input on the build. I'll see if I can add some more information to the docs at http://robolectric.org.

**Pull request closed without merging**
