### PR TITLE
[warning] JavaLangClash warning fix

### PR DESCRIPTION
**Pull request by hellosagar**
### Overview
[JavaLangClash](https://errorprone.info/bugpattern/JavaLangClash) - Never reuse class names from java.lang

### Proposed Changes
Changed the names of the class which is similar to `java.lang` classes

### CODE REVIEW

**Comment by utzcoz** [comment]
@hellosagar could you squash commits to one? Thanks.

**Comment by hellosagar** [comment]
The reason of Test/instrumentation-tests does clear exactly, can we re-run it?

**Review by utzcoz — APPROVED** [review]
LGTM. Thanks.

**Comment by hellosagar** [comment]
@hoisie just a gentle reminder to review 😄

**Pull request merged**
