### PR TITLE
Do not break child-first class loading model for the bootstrap loader

### LINKED ISSUE #2677: Mockito mocking of finals is broken
Robolectric is not compatible with latest Mockito experimental feature for mocking finals:
http://site.mockito.org/mockito/docs/current/org/mockito/Mockito.html#39

Steps:
1. Have a project with Robolectric and Mockito
2. Enable experimental Mockito feature

I'm with Robolectric 3.1.2.

### PR DESCRIPTION
**Pull request by raphw**
A proposal change of the class loader to fix #2677

### CODE REVIEW

**Comment by Daio-io** [comment]
Any idea when this might get merged in?

**Comment by folkyatina** [comment]
It's very crucial for testing Kotlin code on Android.

**Comment by raphw** [comment]
We might have found a workaround for the direct class loading that we want to avoid: https://github.com/mockito/mockito/issues/845

**Comment by eygraber** [comment]
The workaround that @raphw linked did not work. Any way to sneak this into 3.2 😄

**Comment by jongerrish** [comment]
We're going to work on this as a follow up to 3.2, We'll try and release
3.2.1 with this fixed this month.

**Comment by raphw** [comment]
Even after our change, the Robolectrics class loader still expects any such class to be loaded by the child class loader and does not query its parent as a fallback. We missed this. It does now however work on other child-first class loaders like on applications servers.

**Comment by xian** [comment]
Closing in favor of #2905. Thank you for your help @raphw!

@folkyatina, are you still having trouble using Robolectric with Kotlin? If so, could you open a new PR or issue showing the failure? Thanks!

**Pull request closed without merging**
