### PR TITLE
Rebase PR 6265: Bounds check the correct variable.

### PR DESCRIPTION
**Pull request by utzcoz**
Close https://github.com/robolectric/robolectric/pull/6265.

### CODE REVIEW

**Comment by utzcoz** [comment]
Hi @hoisie , it is another rebased PR for old PR. It is very minor and meaningful. Could you take a look at it? Thanks.

**Comment by hoisie** [comment]
Awesome, thanks! Can you also remove the `PiperOrigin-RevId: 361163348` line from the message? It might confuse our internal code sync system.

**Comment by utzcoz** [comment]
> Awesome, thanks! Can you also remove the `PiperOrigin-RevId: 361163348` line from the message? It might confuse our internal code sync system.

Done.

**Comment by utzcoz** [comment]
> Awesome, thanks! Can you also remove the `PiperOrigin-RevId: 361163348` line from the message? It might confuse our internal code sync system.

Does `Message` means commit message? I will update tonight.

**Comment by utzcoz** [comment]
Deleted `PiperOrigin-RevId` from git message, and added myself email as signed-off. @hoisie , I think it can be reviewed again.

**Comment by hoisie** [comment]
Thanks!

**Comment by utzcoz** [comment]
Hi @hoisie , after this PR merged, there is a failed test at CircleCI's task `test_16_17_18` only:

```
expected to be false
	at org.robolectric.shadows.ShadowDisplayEventReceiverTest.closeGuard_autoCloses(ShadowDisplayEventReceiverTest.java:39)
```

This PR doesn't look like related this failed test. Does it mean this test related code not stable?

**Comment by utzcoz** [comment]
> Hi @hoisie , after this PR merged, there is a failed test at CircleCI's task `test_16_17_18` only:
> 
> ```
> expected to be false
> 	at org.robolectric.shadows.ShadowDisplayEventReceiverTest.closeGuard_autoCloses(ShadowDisplayEventReceiverTest.java:39)
> ```
> 
> This PR doesn't look like related this failed test. Does it mean this test related code not stable?

@hoisie It disappears when I run tests at CircleCI for other PRs. Maybe `org.robolectric.shadows.ShadowDisplayEventReceiverTest.closeGuard_autoCloses` is unstable.

**Pull request merged**
