### PR TITLE
Rollback kotlin conversion for utils module

### PR DESCRIPTION
**Pull request by utzcoz**
Revert "test: convert the MyServiceFinderAdapter of utils module from java to kotlin"
This reverts commit b97498455dc38f20de8154c60dec364ecaaee028.

Revert "test: convert the PluginFinderTest of utils module from java to kotlin"
This reverts commit f3d8b508ed2136a4f9de781ef288fffe4d5d6fa1.

Revert "test: convert the TempDirectoryTest for utils module from java to kotlin"
This reverts commit 61e54f69ce2d6de72545d136ca97f5e9e37a7784.

Revert "test: convert the PerfStatsCollectorTest of utils module from java to kotlin"
This reverts commit c73d69adc9400c53d994ffc892b622a1d064d48f.

Revert "refac: convert Java to Kotlin with correct format"
This reverts commit 8e8a01140f20adec395029c9cac58b29f5d13394.

Revert "build: add the kotlin support and code formatter plugin"
This reverts commit 28b70dd04fc68e133c9dd9680c6a05197ccde4f2.

### CODE REVIEW

**Comment by utzcoz** [comment]
Origin Kotlin conversion has brought following dependencies to .pom and .module files for utils module:

```
utils/4.9-SNAPSHOT/utils-4.9-SNAPSHOT.pom:70:      <groupId>org.jetbrains.kotlin</groupId>
utils/4.9-SNAPSHOT/utils-4.9-SNAPSHOT.pom:71:      <artifactId>kotlin-stdlib</artifactId>
utils/4.9-SNAPSHOT/utils-4.9-SNAPSHOT.module:25:        "org.jetbrains.kotlin.localToProject": "public",
utils/4.9-SNAPSHOT/utils-4.9-SNAPSHOT.module:26:        "org.jetbrains.kotlin.platform.type": "jvm"
utils/4.9-SNAPSHOT/utils-4.9-SNAPSHOT.module:58:          "group": "org.jetbrains.kotlin",
utils/4.9-SNAPSHOT/utils-4.9-SNAPSHOT.module:59:          "module": "kotlin-stdlib",
utils/4.9-SNAPSHOT/utils-4.9-SNAPSHOT.module:85:        "org.jetbrains.kotlin.localToProject": "public",
utils/4.9-SNAPSHOT/utils-4.9-SNAPSHOT.module:86:        "org.jetbrains.kotlin.platform.type": "jvm"
utils/4.9-SNAPSHOT/utils-4.9-SNAPSHOT.module:132:          "group": "org.jetbrains.kotlin",
utils/4.9-SNAPSHOT/utils-4.9-SNAPSHOT.module:133:          "module": "kotlin-stdlib",
```

This PR will rollback these commits to reduce potential compatibility problems for next release. And we can discuss it later to restrict Kotlin usage area for Robolectric. cc @hoisie @hellosagar .

**Comment by utzcoz** [comment]
Hi @hoisie @JuliaSullivanGoogle could you help to review this PR? Thanks.

**Comment by hoisie** [comment]
Is there some Gradle logic we can add to exclude this dependency without rolling back?

**Comment by utzcoz** [comment]
> Is there some Gradle logic we can add to exclude this dependency without rolling back?

We can add script to exclude kotlin-stdlib from utils .pom file, but I don't know how to exclude it from .module file, especially exclude `"org.jetbrains.kotlin.localToProject": "public",` and `"org.jetbrains.kotlin.platform.type": "jvm"`. I have pasted my trying at Slack channel.

**Comment by utzcoz** [comment]
Hi @kingargyle, do you have any idea about it?

**Comment by kingargyle** [comment]
Gradle has docs on how to exclude transitive dependencies.

https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html

**Comment by utzcoz** [comment]
> Gradle has docs on how to exclude transitive dependencies.
> 
> https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html

Thanks. Looks like it is used for user part. I will try it and similar things to check whether it can help to remove transitive dependencies from Robolectric released modules directly. The ideal occasion is that user will not add extra scripts at build.gradle or build.gradle.kts to use new Robolectric release.

**Comment by kingargyle** [comment]
The other option you have is a custom resolution strategy to exclude the particular items you don't want to bring down.

**Comment by utzcoz** [comment]
> The other option you have is a custom resolution strategy to exclude the particular items you don't want to bring down.

I will try it at https://github.com/robolectric/robolectric/pull/7497. Thanks.

**Pull request closed without merging**
