### PR TITLE
[WIP] Update BouncyCastle (1.52 -> 1.58) dependency

### PR DESCRIPTION
**Pull request by alixwar**
### Overview
https://www.bouncycastle.org/latest_releases.html
https://www.bouncycastle.org/releasenotes.html

### Proposed Changes
Update dependency to the latest minor/patch version (1.58). I noticed the old dependency when I noticed a build error when upgrading to Robolectric 3.5.1 (dependency conflicts).

### CODE REVIEW

**Comment by kingargyle** [comment]
@alixwar There is a reason that it is at 1.52, as there was some compatibility issues with some of the JDKs.   See the 3.5.1 release notes, and a work around for some jdks here. https://github.com/robolectric/robolectric/issues/3288#issue-245935102

**Comment by alixwar** [comment]
@kingargyle it would be good to have a test that fails when bc is upgraded

**Comment by alixwar** [comment]
@kingargyle Am I blind? I read that the issue is solved by forcing a newer version of bc than the one specified in robolectric. So this PR should be fine?

**Comment by kingargyle** [comment]
It's a work around, not an actual fix.  The actual fix is for Bouncy Castle to correct their issue.   They can't force an upgrade as they don't know what JVM that people have.  You can use the work around if it works for you but the goal is to make sure this works regardless of what java 1.8 JVM is used.  I'm not a committer here so it is up to the maintainers to make the call, I just know they rolled back because of SSL issues.

**Comment by alixwar** [comment]
@kingargyle Ok. I fail to find a reference to the original issue causing the rollback. It would be good to be able to clearly track the real issue at BouncyCastle if they acknowledge this as a problem on their side

**Comment by kingargyle** [comment]
@alixwar this comment outlines the issue. https://github.com/robolectric/robolectric/issues/3288#issuecomment-338658566

**Comment by alixwar** [comment]
@kingargyle Thanks. I scrolled right passed it. Doesn't seem to be reported at BouncyCastle. I'll see what I can do

**Comment by alixwar** [comment]
I've now reported it in their issue tracker: https://github.com/bcgit/bc-java/issues/249

**Comment by cesar1000** [comment]
Also, the latest version of bouncycastle uses /dev/random by default for random number generation, which may block for a long time as the system accumulates entropy. While this can be configured, it's a relevant change of behavior that can be painful if running Robolectric extensively in CI servers.

**Comment by utzcoz** [comment]
Hi @alixwar , thanks for your contribution. The BouncyCastle dependency of Robolectric has been upgraded to 1.68. Thanks.

**Pull request closed without merging**
