### PR TITLE
Add a dummy shadow for the MultiDex class loader

### LINKED ISSUE #1328: Multidex support
Running into the following after converting my application to a MultiDexApplication:

```
java.lang.VerifyError: Expecting a stackmap frame at branch target 46
Exception Details:
  Location:
    android/support/multidex/MultiDexApplication.<init>()V @18: ifnull
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ab7 001f 2ab6 0022 1224 0312 02b8 002a
    0x0000010: 4c2b c600 1c2b 2a2a b600 2e03 bd00 30b9
    0x0000020: 0036 0400 57a7 0014 4d2c b800 3abf 2ab7
    0x0000030: 001a b14d 2cb8 003a bfb1               
  Exception Handler Table:
    bci [21, 37] => handler: 40
    bci [46, 50] => handler: 51

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:77)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

### PR DESCRIPTION
**Pull request by sschuberth**
This fixes #1328 if the shadow is globally used e.g. by adding

    shadows=org.robolectric.shadows.ShadowMultiDex

to "org.robolectric.Config.properties".

### CODE REVIEW

**Comment by jongerrish** [comment]
This is part of a dedicated multidex support library so you will probably
be asked to create a separate subproject for it similar to:

https://github.com/robolectric/robolectric/tree/master/robolectric-shadows/shadows-support-v4

but called

https://github.com/robolectric/robolectric/tree/master/robolectric-shadows/shadows-support-multidex

**Comment by sschuberth** [comment]
@jongerrish Yeah, I was considering that, but given that this only is a single file (and will probably never become more than that) I though creating a separate directory would be too much overhead.

**Comment by sschuberth** [comment]
Looking at the Travis CI output, I realize Roboletric is built with Maven, not Gradle. However, the MultiDex library is only available as an AAR, not as a JAR. Can the Travis CI installation of Maven handle AARs?

**Comment by erd** [comment]
> Yeah, I was considering that, but given that this only is a single file (and will probably never become more than that) I though creating a separate directory would be too much overhead.

The reason they are separate module is to limit the number of external dependencies placed on the core Robolectric module. It also prevents transitive dependencies from being imposed on downstream users.

> Can the Travis CI installation of Maven handle AARs?

Not as it is currently implemented. We'll probably have to have a script that extracts the classes.jar from the archive and uses `mvn install:install-file` to place it in the local repo.

**Comment by erd** [comment]
I moved the shadow into its own add-on module (org.robolectric:shadows-multidex), so it'll be loaded by Robolectric automatically when the module is included. Thanks for the PR!

**Comment by sschuberth** [comment]
Thanks for the fixup!

**Comment by spartacus777** [comment]
So, I added config file org.robolectric.Config.properties to Assets folder, made dependency from 
testCompile 'org.robolectric:shadows-multidex:3.0-SNAPSHOT'  but still have the same mistake (shadows-multidex:3.0-SNAPSHOT was made 16th Jan, 2015, and it has your commit). Tell me please, what do I do wrong?

**Comment by sschuberth** [comment]
The Assets folder is not in you classpath by default. you need to put the org.robolectric.Config.properties file into a folder that is in your classpath, or add the Assets folder to you classpath.

**Comment by spartacus777** [comment]
@sschuberth , can you give me an example how to add  Assets folder to my classpath.Should I do it throw build.gradle ? Or what folder (how to investigate it) is in my classpath? 
I am new to gradle build system

**Comment by sschuberth** [comment]
It depends a bit on how you've integrated Robolectric into your Android build. I'm using the [android-unit-test](https://github.com/JCAndKSolutions/android-unit-test) Gradle plugin. With that you could do something like

```groovy
androidUnitTest {
    sourceSets {
        test {
            resources.srcDirs = ['assets']
        }
    }
}
```

However, I recommend against adding the `assets` directory to your classpath. The files you'd usually put in there do not belong into classpath. Instead, create a separate resources directory for the unit tests.

**Comment by simtse** [comment]
Hey erd, you created the module (org.robolectric:shadows-multidex) to include the shadowed multitex. I am building by projects with gradle right now and I put the following

```
androidTestCompile 'org.robolectric:shadows-multidex:3.0-SNAPSHOT'
```

and my repositories are
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.robolectric:robolectric-gradle-plugin:0.13.+'
    }
}
```

but I would get 

```
Failed to resolve: org.robolectric:shadows-multidex:3.0-SNAPSHOT
```

What else do  I have to do in order to get this shadow loaded? shadow=ShadowMultiDex.class?

**Comment by simtse** [comment]
So I formulated my situation with more information. I was wondering if you could help me see if I am doing something totally wrong in my setup of ShadowMultiDex and gradle thanks!

http://stackoverflow.com/questions/29022549/android-multidex-app-cant-run-robolectric-unit-tests

**Comment by jongerrish** [comment]
Stack trace?

**Comment by simtse** [comment]
```
java.lang.RuntimeException: java.lang.NullPointerException
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:227)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:167)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.robolectric.manifest.MetaData.init(MetaData.java:55)
	at org.robolectric.manifest.AndroidManifest.initMetaData(AndroidManifest.java:367)
	at org.robolectric.res.builder.DefaultPackageManager.addManifest(DefaultPackageManager.java:398)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:71)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:420)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:223)
	... 35 more
```

**Comment by jongerrish** [comment]
What entries do you have in your <meta-data> elements?

Basically its trying to load a resource like this:-

<meta-data android:name="zoo" android:value="@string/kangaroo" />

But it can't find @string/kangeroo

You probably have some reference in your meta-data that is declared in a
library that Robolectric doesn't know about.

You using gradle or mvn or something else?

**Comment by bvellacott** [comment]
Thanks for that!

**Comment by tommyd3mdi** [comment]
I guess its still the easiest thing to catch the `RuntimeException` stemming from `MultiDex.install()`, right?

**Comment by sschuberth** [comment]
No, if you use the optional `org.robolectric:shadows-multidex` module there should be no `RuntimeException` while running unit tests anymore.

**Pull request closed without merging**
