### PR TITLE
Add initial wallpaper manager shadow.

### PR DESCRIPTION
**Pull request by gruszczy**

### CODE REVIEW

**Comment by erd** [comment]
Please add some basic tests that show how to use this shadow. The tests not only verify that the shadow code is correct, but help us when we update Robolectric to support new versions of Android.

**Comment by erd** [comment]
This PR somehow included a test for `ShadowPowerManager` that was named `ShadowWallpaperManagerTest.java`. I have a feeling the changes here got mixed with #1448. Next time you submit a pull request, you might want to create your change on a feature branch to avoid mingling different changes.

**Comment by gruszczy** [comment]
I will definitely try. Sorry about the confusion, I use some git at work, but branches and uploading is managed through repo and gerrit, so I get confused when I use pure git.

**Comment by erd** [comment]
No worries :) Thanks for the PR!

**Pull request closed without merging**
