### PR TITLE
Make ShdadowVibrator compatible with SDK 28+

### PR DESCRIPTION
**Pull request by utzcoz**
Fixes: https://github.com/robolectric/robolectric/issues/8137.

### CODE REVIEW

**Comment by paulsowden** [comment]
Interesting, I can reproduce this inside of Google test environment when I disable the internal class instrumenting we have enabled. I wonder what's different about the tests that are running presubmit on github automation compared to the integration compat test, is it using different jars?

**Comment by hoisie** [comment]
@utzcoz as a start what about just entirely removing the `getVibrationEffectSegments` method. It seems to have been mistakenly added. This method is totally useless because one cannot even do anything related to VibrationEffectSegment without using reflection.

**Comment by hoisie** [comment]
Actually maybe `getVibrationEffectSegments` it should have been a package-protected `@VisibleForTesting` method.

**Comment by hoisie** [comment]
Yeah I think this is overkill.

1) Remove the getVibrationEffectSegments method completely, including all tests that reference it

2) Use `List<Object> vibrationEffectSegments`

**Comment by utzcoz** [comment]
> I wonder what's different about the tests that are running presubmit on github automation compared to the integration compat test, is it using different jars?

@paulsowden GitHub Actions don't use special configuration of instrumenting. But the difference of the compat-target28's building configuration will cause different result. GitHub Actions uses SDK 28 jars as the compiling dependency, and it doesn't contain the class code of `VibrationEffectSegment` and other classes introduced from higher SDK than 28. If the internal Bazel/Gradle/Blaze configuration uses SDK 33 or other jar that contains these classes as the dependency, I think this issue can't be reproduced.

**Comment by utzcoz** [comment]
> Yeah I think all we need is:
> 
>     1. Remove the getVibrationEffectSegments method completely, including all tests that reference it
> 
>     2. Use `List<Object> vibrationEffectSegments`

@hoisie Just updating the PR based on this suggestion. The `VibrationAttributes` is also a new class that introduced from the higher SDK.

**Comment by utzcoz** [comment]
@paulsowden @hoisie Maybe PTAL? And can someone help to do an internal compatibility validation?

**Comment by paulsowden** [comment]
Sorry there was no compatibility issue internally, I was just curious why this wasn't showing up in all tests, it seems like if this is a constraint then we should make the main unit test suite fail in these situations. Seems like it should be possible using a lint check, Robolectric linters already catch signature mismatch based on sdk version so it clearly knows.

**Review by paulsowden — APPROVED** [review]

**Comment by utzcoz** [comment]
@paulsowden Thanks for confirmation.

> I was just curious why this wasn't showing up in all tests, it seems like if this is a constraint then we should make the main unit test suite fail in these situations

The main test suite always uses all SDK android-all jars as dependencies, and they contain all new packages. The compat-target28 test suite uses SDK 28 android-all jar as dependency only to catch these compatibility issues. Actually we have encountered many times of issues with this type.  I recommend Googlers to add necessary tests to compat-target28 test suite when you support new APIs to ensure it will not break low SDK compatibility.

**Pull request merged**
