### PR TITLE
Use setup prepared fields for ShadowActivityManagerTest

### PR DESCRIPTION
**Pull request by utzcoz**

### CODE REVIEW

**Comment by utzcoz** [comment]
Hi @hoisie , could you help to review this little refactor PR? Thanks.

**Comment by utzcoz** [comment]
I will rebase it later.

**Comment by utzcoz** [comment]
Hi @hoisie , I rebased it, and could you help to review this little refactor PR? Thanks.

**Comment by hoisie** [comment]
Looking into this now

**Comment by hoisie** [comment]
Thanks for the cleanup

**Pull request merged**
