### PR TITLE
4078 - remove maxpermsize

### PR DESCRIPTION
**Pull request by jaredsburrows**
@xian @jongerrish Closes https://github.com/robolectric/robolectric/issues/4078.

### CODE REVIEW

**Comment by xian** [comment]
Causes tests to exit with:
`Process 'Gradle Test Executor 18' finished with non-zero exit value 137`

**Comment by jaredsburrows** [comment]
The JVM says this is being ignored. It looks like it is running Java 1.8 on the CI.

**Comment by xian** [comment]
Seems like they're still failing. :-/

**Comment by jaredsburrows** [comment]
@xian Good to merge?

**Comment by jaredsburrows** [comment]
@xian Good to merge?

**Comment by utzcoz** [comment]
Hi @jaredsburrows , looks like `MaxPermSize` already disappeared from Robolectric's `RoboJavaModulePlugin`. Feel free to reopen this PR if think it still useful.

**Pull request closed without merging**
