### PR TITLE
Shadow for GoogleApiAvailability.

### PR DESCRIPTION
**Pull request by diegotori**
Partially addresses Issue #2215. The Shadow for GoogleApiClient and its Builder is still a WIP on another branch in my fork. Created initial Shadow for GoogleApiAvailability. Also upgrades shadows-play-services' POM to version 23.1.1 of the Support Library as well as version 8.4.0 of Google Play Services Base and Basement. Also updated the Play Services version in scripts/install-dependencies.rb.

### CODE REVIEW

**Comment by mag** [comment]
@diegotori The Travis build is breaking, and I'm not sure why.  Two jobs were run and one failed, and the reason for the failure in the second one is hard to decipher.

I'm hoping somebody with a little bit more experience with the Travis build can interpret the tea leaves. @jongerrish or @erd?

**Comment by erd** [comment]
I've restarted the build. Let's give it one more chance to go through.

**Comment by diegotori** [comment]
Looks like it passed on all of them this time. Perhaps it was a fluke as to why one of them failed last night .

**Comment by jongerrish** [comment]
That Java 8 build it pretty flaky. If it fails just restart it, usually
works ;-)

**Comment by diegotori** [comment]
Re-synced the branch with the latest master changes. Knock-on-wood TravisCI doesn't crap out like last time.

**Comment by asuraphel** [comment]
@erd Will you guys merge this today?

**Comment by diegotori** [comment]
@erd, is this PR still on track for merging any time soon? Just curious, since it's been a while and @asuraphel was dependent on it making master.

**Comment by jongerrish** [comment]
This looks fine to me, can you want to merge with master and get a green build.

@fiower there is some overlap here with https://github.com/robolectric/robolectric/pull/2374

**Comment by diegotori** [comment]
@fiower You may wanna sync my changes against yours. In particular, ensure that it's using play services 8.4.0. Aside from that, if this gets merged today, I will fast follow with any changes that I can port back to my ShadowGoogleApiAvailability hopefully this week.

@jongerrish just re-synced the branch with master's changes, awaiting TravisCI to give the all clear, then you can merge when ready.

**Pull request merged**
