### PR TITLE
Migrate ActivityTestRule to ActivityScenario

### LINKED ISSUE #7036: Migrate ActivityTestRule to ActivityScenario for Robolectric's tests as much as possible
### Description

Migrate deprecated `ActivityTestRule` to `ActivityScenario` for Robolectric's tests as much as possible, except `ActivityTestRuleTest` for `ActivityTestRule`. For example `EspressoTest` under inregration_tests:androidx_test and `ActivityTest` under integration_tests:ctesque. 

### Steps to Reproduce

None.

### Robolectric & Android Version

Current master branch.

### Link to a public git repo demonstrating the problem:

Robolectric itself.

### PR DESCRIPTION
**Pull request by akhilrm**
### Overview

Fixes #7036
Migrate ActivityTestRule to ActivityScenario or ActivityScenarioRule for tests

### CODE REVIEW

**Review by utzcoz — APPROVED** [review]
LGTM. Thanks.

**Comment by utzcoz** [comment]
Hi @JuliaSullivanGoogle , could you help to review and verify internally for this PR? I know some tests of `androidx_test`, for example `EspressoTest` will be run with Emulator, and current GitHub CI doesn't check this occasion. Maybe it needs your help to verify it internally. Thanks.

**Review by hoisie — APPROVED** [review]

**Comment by hoisie** [comment]
@utzcoz it's safe to merge, we can fix any issues internally

**Comment by utzcoz** [comment]
> @utzcoz it's safe to merge, we can fix any issues internally

Done. Merged.

**Pull request merged**
