### PR TITLE
Fix #1314

### LINKED ISSUE #1314: Combining Contenprovider with addOnAccountsUpdatedListener
I try to query a content provider, that also implements addOnAccountsUpdatedListener. The Listener itself query also the contentprovider if he is called. This causes a stackoverflow because recursive calling. 

It seems like robolectric is creating a new contentprovider and accountmanager on each query.

[Stacktrace](http://zero.azapps.de/?fcd76cb274aae437#XpdaIvkXngpG3shi69ThBdZxsNNg63eHBgSn3iQhIxI=)

### PR DESCRIPTION
**Pull request by weiznich**
* Add contentprovider to map before calling contentprovider.onCreate(),
because onCreate could call the contentprovider

### CODE REVIEW

**Comment by coreydowning** [comment]
Can you add a test that demonstrates the previously broken behavior?

**Comment by erd** [comment]
Could you please add a regression test?

**Comment by weiznich** [comment]
Sorry, currently I am very busy with other things. So I don't have time to write any big test for this.

The issue happens if someone calls the contentprovider while it is constructed (for example in onCreate of the contentprovider).

**Comment by erd** [comment]
I'm sorry, but pull-requests need to be accompanied with tests. Feel free to re-open if you get a chance to add tests for this.

**Pull request closed without merging**
