### PR TITLE
DefaultPackageManager: make intent comparator more thread-safe

### PR DESCRIPTION
**Pull request by holmari**
It's possible that the code under test modifies intents in a different
thread than main, causing the comparator to crash to an NPE at various
points.

### CODE REVIEW

**Comment by holmari** [comment]
Stacktrace (that I only ran into twice during porting to robolectric 3) can be found here, http://pastebin.com/f7YUYjM6

I couldn't debug the actual root cause of failure since it happened too rarely.

**Comment by lexs** [comment]
Do you know if this actually fixes this? The tracking issue is https://github.com/robolectric/robolectric/issues/1626

**Comment by holmari** [comment]
I can't reliably reproduce it so I'm not really sure. Thanks for linking to the ticket, I didn't know one existed.

Seeing that you've also investigated it and had same ideas, I'd argue for merging it in even if we're not sure it fully fixes the problem because it doesn't make the issue worse.

**Comment by lexs** [comment]
I'm all for merging, this code is slightly cleaner anyways.

**Comment by erd** [comment]
Thanks @holmari !

**Pull request merged**
