### PR TITLE
Deprecate the supportv4 shadows as mentioned in #6185

### PR DESCRIPTION
**Pull request by alsutton**
### Overview

Deprecating the supportv4 shadows. It seems not a lot of folk are going to be using them going forward.

### Proposed Changes

Marked the supportv4 shadows with @Deprecated

### CODE REVIEW

**Comment by hoisie** [comment]
Thanks for doing this. Should be fine to Merge. Just one question: what are you using instead of https://github.com/robolectric/robolectric/blob/master/shadows/supportv4/src/main/java/org/robolectric/shadows/support/v4/SupportFragmentController.java? AndroidX Test FragmentScenario? I think most of the shadows are obsolete, but I've used SupportFragmentController in the past and it was useful. I suppose if folks need it they can depend on shadows.supportv4 4.5.x.

**Comment by hoisie** [comment]
I realized that removing them in one fell sweep right now is not consistent with how deletions are usually done in Robolectric. SupportFragmentController, the most widely used class here, has not been officially deprecated yet. I'd be fine with marking everything here deprecated and then removing it in 4.7. WDYT?

**Comment by alsutton** [comment]
Yup, We're using androidx FragmentScenario to do fragment testing. I'll update the PR to deprecate everything in the next week or two.

**Comment by alsutton** [comment]
Looks like there's a problem on the publish action. The error is;

github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"}

**Comment by alsutton** [comment]
Rebased past test reporting issue, all good now.

**Comment by utzcoz** [comment]
@hoisie I found this PR also can fix the issue https://github.com/robolectric/robolectric/issues/4578.

**Review by utzcoz — APPROVED** [review]
LGTM. Hi @hoisie , what about merging it to deprecate on 4.7, and remove it on 4.8?

**Comment by utzcoz** [comment]
Hi @alsutton , could you help to rebase this PR? `SwipeRefreshLayout` has been deprecated by one old commit. Thanks.

**Comment by alsutton** [comment]
No problem. Done.

**Review by utzcoz — APPROVED** [review]
LGTM. Hi @hoisie could you help to check this PR again? Thanks.

**Pull request merged**
