### PR TITLE
[warning] UnnecessaryParentheses warning fix

### PR DESCRIPTION
**Pull request by hellosagar**
### Overview
[UnnecessaryParentheses](https://errorprone.info/bugpattern/UnnecessaryParentheses) - These grouping parentheses are unnecessary; it is unlikely the code will be misinterpreted without them.

### Proposed Changes
Removed the unnecessary parentheses.

### CODE REVIEW

**Comment by utzcoz** [comment]
@hellosagar could you sqaush commits to one? Thanks. Some parentheses maybe left when converting C/C++ to Java. Some methods look like macro in C/C++, and it's safe to add parentheses  to marco's calling.

**Comment by hellosagar** [comment]
@utzcoz Sorry, can you refer to me specific code for which parentheses is needs to be added there we can suppress the warning

**Comment by utzcoz** [comment]
> @utzcoz Sorry, can you refer to me specific code for which parentheses need to be added there we can suppress the warning

I don't find any should be supress. The above is used to try to explain why there are some parentheses. You can omit it.

**Comment by hoisie** [comment]
Thanks!

**Pull request merged**
