### PR TITLE
Adding source implementation in shadowaccessibilityrecord

### PR DESCRIPTION
**Pull request by yuzhong-google**

### CODE REVIEW

**Comment by jaredsburrows** [comment]
Can you add tests for the additional methods?

**Comment by yuzhong-google** [comment]
will do, thanks

**Comment by yuzhong-google** [comment]
Hi @jaredsburrows tests added.

**Comment by jaredsburrows** [comment]
Awesome!

Jared Burrows

jaredsburrows@gmail.com

My Resume: https://www.linkedin.com/in/jaredsburrows

**Pull request merged**
