### PR TITLE
Add Apple Silicon support for libsqlite4java

### LINKED ISSUE #6311: Apple Silicon support
### Description
When perform robolectric test on Apple silicon, following error is raised

```
    Caused by: com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/xp/t20n_5q54v9d7dz1rt9bk9k40000gp/T/1616114208715-0/libsqlite4java.dylib: dlopen(/private/var/folders/xp/t20n_5q54v9d7dz1rt9bk9k40000gp/T/1616114208715-0/libsqlite4java.dylib, 1): no suitable image found.  Did find:
    	/private/var/folders/xp/t20n_5q54v9d7dz1rt9bk9k40000gp/T/1616114208715-0/libsqlite4java.dylib: no matching architecture in universal wrapper
    	/private/var/folders/xp/t20n_5q54v9d7dz1rt9bk9k40000gp/T/1616114208715-0/libsqlite4java.dylib: no matching architecture in universal wrapper
    	at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:97)
    	at com.almworks.sqlite4java.SQLite.getSQLiteVersion(SQLite.java:114)
    	at org.robolectric.shadows.util.SQLiteLibraryLoader.loadFromDirectory(SQLiteLibraryLoader.java:90)
    	at org.robolectric.shadows.util.SQLiteLibraryLoader.doLoad(SQLiteLibraryLoader.java:55)
    	at org.robolectric.shadows.util.SQLiteLibraryLoader.load(SQLiteLibraryLoader.java:39)
    	at org.robolectric.shadows.ShadowSQLiteConnection.nativeOpen(ShadowSQLiteConnection.java:73)
    	at org.robolectric.shadows.ShadowSQLiteConnection.nativeOpen(ShadowSQLiteConnection.java:80)
    	at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)

....
    Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/xp/t20n_5q54v9d7dz1rt9bk9k40000gp/T/1616114208715-0/libsqlite4java.dylib: dlopen(/private/var/folders/xp/t20n_5q54v9d7dz1rt9bk9k40000gp/T/1616114208715-0/libsqlite4java.dylib, 1): no suitable image found.  Did find:
    	/private/var/folders/xp/t20n_5q54v9d7dz1rt9bk9k40000gp/T/1616114208715-0/libsqlite4java.dylib: no matching architecture in universal wrapper
    	/private/var/folders/xp/t20n_5q54v9d7dz1rt9bk9k40000gp/T/1616114208715-0/libsqlite4java.dylib: no matching architecture in universal wrapper
    	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
    	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
    	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
    	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
    	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
    	at java.base/java.lang.Runtime.load0(Runtime.java:768)
    	at java.base/java.lang.System.load(System.java:1837)
    	at com.almworks.sqlite4java.Internal.tryLoadFromPath(Internal.java:340)
    	at com.almworks.sqlite4java.Internal.loadLibraryX(Internal.java:110)
    	at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:95)
    	... 36 more

```

### Robolectric & Android Version
 JVM : Jetbrains Runtime from Intellij IDEA 2020.3.2 ( OpenJDK 64-Bit Server VM JBR-11.0.9.1.11-1145.77-jcef (build 11.0.9.1+11-b1145.77, mixed mode) )
 Robolectric : 4.5.1
 Android Compile SDK : 30

### PR DESCRIPTION
**Pull request by ganadist**
### Overview
Add Apple Silicon Support

### Proposed Changes
Add `libsqlite4java.dylib` for Apple Silicon

Fix #6311

### CODE REVIEW

**Comment by hoisie** [comment]
Wow, this is amazing, thanks.

@ZacSweers can you verify that it works for you? Instructions here: https://github.com/robolectric/robolectric/wiki/Running-Robolectric-SNAPSHOThttps://github.com/robolectric/robolectric/wiki/Running-Robolectric-SNAPSHOT

**Comment by ZacSweers** [comment]
Will give this a try!

**Comment by ZacSweers** [comment]
I gave it a try, and while it does get farther, I ran into this issue

```
android.database.sqlite.SQLiteException: Cannot prepare statement, base error code: 1
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getSqliteException(ShadowSQLiteConnection.java:849)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getFuture(ShadowSQLiteConnection.java:819)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:807)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:437)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:91)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.__constructor__(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java)
	at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:994)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.compileStatement(FrameworkSQLiteDatabase.java:64)
	at com.squareup.sqldelight.android.AndroidSqliteDriver$execute$1.invoke(AndroidSqliteDriver.kt:138)
	at com.squareup.sqldelight.android.AndroidSqliteDriver$execute$1.invoke(AndroidSqliteDriver.kt:19)
	at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:119)
	at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:138)
	at slack.corelib.accountmanager.AppScopedSqlDelightDbCallbackTest.Verify upgrade path from V9 to V11(AppScopedSqlDelightDbCallbackTest.kt:526)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:568)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.almworks.sqlite4java.SQLiteException: [1] DB[175] prepare() INSERT INTO accounts(user_id, team_id, email, token, enterprise_id, last_accessed, team_blob)
SELECT ?, ?, ?, ?, ?, ?, ? [no such table: main.enterprise_old]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:201)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getFuture(ShadowSQLiteConnection.java:813)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:807)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:437)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:91)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.$$robo$$android_database_sqlite_SQLiteConnection$acquirePreparedStatement(SQLiteConnection.java:887)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.$$robo$$android_database_sqlite_SQLiteConnection$prepare(SQLiteConnection.java:498)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java)
	at android.database.sqlite.SQLiteSession.$$robo$$android_database_sqlite_SQLiteSession$prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java)
	at android.database.sqlite.SQLiteProgram.$$robo$$android_database_sqlite_SQLiteProgram$__constructor__(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java)
	at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$compileStatement(SQLiteDatabase.java:994)
	at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.compileStatement(FrameworkSQLiteDatabase.java:64)
	at com.squareup.sqldelight.android.AndroidSqliteDriver$execute$1.invoke(AndroidSqliteDriver.kt:138)
	at com.squareup.sqldelight.android.AndroidSqliteDriver$execute$1.invoke(AndroidSqliteDriver.kt:19)
	at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:119)
	at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:138)
	at slack.corelib.accountmanager.AppScopedSqlDelightDbCallbackTest.Verify upgrade path from V9 to V11(AppScopedSqlDelightDbCallbackTest.kt:526)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 15 more
Caused by: com.almworks.sqlite4java.SQLiteException: [1] DB[175] prepare() INSERT INTO accounts(user_id, team_id, email, token, enterprise_id, last_accessed, team_blob)
SELECT ?, ?, ?, ?, ?, ?, ? [no such table: main.enterprise_old]
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1436)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:580)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:635)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:622)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:442)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:439)
	... 4 more
```

**Comment by ganadist** [comment]
In my case, I tried to test with https://github.com/cashapp/sqldelight and modified robolectric 4.5.1 (cherry-picked from this PR).

with vanilla robolectric 4.5.1 : https://scans.gradle.com/s/d3wzq4gtu4dt4/tests
with modified robolectric 4.5.1 : https://scans.gradle.com/s/5b3rkfwtcz73e/tests

**Comment by ganadist** [comment]
Here are test results with robolectric master ( bbef5c19 ) + This PR.

Apple Silicon: https://scans.gradle.com/s/hrbpzmryg2pp6/tests
Linux : https://scans.gradle.com/s/jy3sgxmg7urxc/tests

It seems there are other issues on master branch.

**Comment by bopbi** [comment]
@ganadist it seems this PR need to be rebased

**Comment by bopbi** [comment]
@ganadist thanks for update your branch

**Comment by bopbi** [comment]
@ZacSweers could you explain which test that you are running ?

**Comment by ZacSweers** [comment]
They're tests in our internal repo

**Comment by ganadist** [comment]
Already fixed since robolectric 4.7

**Pull request closed without merging**
