### PR TITLE
Backport FindJNI.cmake from cmake v3.22.0

### PR DESCRIPTION
**Pull request by utzcoz**
Backport `FindJNI.cmake` from cmake v3.22.0 with better Windows and aarch64 supporting.

### CODE REVIEW

**Comment by utzcoz** [comment]
Looks likes module added in [CMAKE_MODULE_PATH](https://cmake.org/cmake/help/latest/variable/CMAKE_MODULE_PATH.html) has higher priority than default in cmake. We can test it if we can ensure current PR works for us. 

I will test it on Windows.

**Comment by hoisie** [comment]
We only need couple of java headers, seems like adding the entire findjni is overkill. If we require JAVA_HOME to be set, would this just work:

```cmake
include_directories($ENV{JAVA_HOME}/include)

if (CMAKE_HOST_SYSTEM_NAME MATCHES "Linux")
  include_directories($ENV{JAVA_HOME}/include/linux)
elif (CMAKE_HOST_SYSTEM_NAME MATCHES "Darwin")
  include_directories($ENV{JAVA_HOME}/include/darwin)
elif (CMAKE_HOST_SYSTEM_NAME MATCHES "Windows")
  include_directories($ENV{JAVA_HOME}/include/win322)
endif()
```

**Comment by utzcoz** [comment]
It's more concise than current full `FindJNI`. But it adds a new `JAVA_HOME` environment dependency. In Linux, `FindJNI` doesn't need `JAVA_HOME`, and it can find real java home correctly. If need, I can create a new PR for only `including` with `JAVA_HOME`.

**Comment by hoisie** [comment]
The CMake I am using already has v 3.22.0 of cmake:
```
$ pacman -Ss cmake
mingw64/mingw-w64-x86_64-cmake 3.22.0-2 [installed]
    A cross-platform open-source make system (mingw-w64)
msys/cmake 3.22.0-1 [installed]
    A cross-platform open-source make system
```

Do these versions not contain the fixes to findJNI?

**Comment by utzcoz** [comment]
The v3.22.0 contains fixes I found for `FindJNI`. Does it also have problem on Windows?

**Comment by utzcoz** [comment]
I renamed `FindROBOJNI` to `FindJNI` to try to fix warnings when testing it on Windows.

**Comment by utzcoz** [comment]
> What about just this? It seems like JAVA_HOME is required on Windows anyway, so a lot of the logic in findJni may not even be relevant for windows:
> 
> ```cmake
> IF (WIN32)
>   if(NOT DEFINED ENV{JAVA_HOME})
>     message(FATAL_ERROR "JAVA_HOME is required in Windows")
>   endif()
>   # find_package JNI is broken on Windows, manually include header files
>   set(JNI_INCLUDE_DIRS "$ENV{JAVA_HOME}/include" "$ENV{JAVA_HOME}/include/win32")
> ELSE()
>   find_package(JNI REQUIRED)
> ENDIF()
> ```

It's more concise than before. I created a related PR https://github.com/robolectric/robolectric/pull/6914 for it.

**Comment by utzcoz** [comment]
I will test it on Windows, and close this PR.

**Pull request closed without merging**
