### PR TITLE
Migrate useLegacy and JUnit assumeTrue/False to TruthJUnit assme

### PR DESCRIPTION
**Pull request by utzcoz**
Fixes: https://github.com/robolectric/robolectric/issues/7689.

### CODE REVIEW

**Comment by utzcoz** [comment]
@hoisie Should we prefer to `org.junit.Assume.assumeTrue/False` or `com.google.common.truth.TruthJUnit.assume`?

**Comment by hoisie** [comment]
I tend to use `com.google.common.truth.TruthJUnit.assume`

**Comment by utzcoz** [comment]
> I tend to use `com.google.common.truth.TruthJUnit.assume`

Okay. I will do a convertion from JUnit's one to `TruthJunit` with this PR this weekend.

**Comment by utzcoz** [comment]
@hoisie Updated. PTAL.

**Comment by utzcoz** [comment]
@hoisie Friendly ping for reviewing.

**Pull request merged**
