### PR TITLE
Migrate to use platform InstrumentationRegistry for LocalActivityInvoker

### PR DESCRIPTION
**Pull request by utzcoz**
Close https://github.com/robolectric/robolectric/issues/6781.

### CODE REVIEW

**Comment by utzcoz** [comment]
Hi @hoisie , @brettchabot , could you help to review this PR? I think this migration is safe because the removed deprecated APIs use the new APIs, used by this PR.

**Comment by hoisie** [comment]
Thanks, reviewing this today.

**Comment by utzcoz** [comment]
> Thanks, reviewing this today.

Thanks. Because there are many merged commits after it pushed, I rebased to current master to give it the latest CI checking.

**Comment by utzcoz** [comment]
Re-run all jobs, and CI passed now.

**Pull request merged**
