### PR TITLE
Support to open fd for uncompressed file in asset

### PR DESCRIPTION
**Pull request by utzcoz**
### Overview

This PR tries to support open asset file with fd for uncompressed file. 

### Proposed Changes

Re-enable ignore test for open asset file with fd and use local header extra length to calculate file content offset in zip for `FileMap` to ensure it can read correct content from zip. Because AGP-7.1.0-alpha08 fixes `noCompress` support for unit test build, so this PR also update ctesque module AGP version to it, and add `noCompress` for test files.

Fix: https://github.com/robolectric/robolectric/issues/5442, https://github.com/robolectric/robolectric/issues/4091

### CODE REVIEW

**Comment by utzcoz** [comment]
There are two things are to be done: bumping ctesque's AGP version to 7.1.0-alpha08, and add `noCompress` for test files. If https://github.com/robolectric/robolectric/pull/6570 is merged before this, this PR should add ensure it can correctly with instrumentation tests (maybe I should check `noCompress` flag only). cc @hoisie @xunkai55 .

**Comment by utzcoz** [comment]
AGP 7.1.0-alpha08 is released, I will try to integrate it to this PR to test `noCompress` support.

**Comment by utzcoz** [comment]
> AGP 7.1.0-alpha08 is released, I will try to integrate it to this PR to test `noCompress` support.

I use test app to test 7.1.0-alpha08, and its `noCompress` support works fine. But it is difficult to integrate AGP 7.1.0-alpha08 to ctesque. I have tried to use new AGP version for ctesque only, but it is omitted, because it is a library for entire project, and its AGP version is replaced by `buildSrc` and project configuration. The AGP 7.1.0-alpha08 needs gradle 7.1.0, and gradle 7.1.0 will cause testapp's class not found problem when running test. Hi @hoisie , do you have some suggestion for this integration problem? Thanks.

**Comment by utzcoz** [comment]
Hi @hoisie , I create a example app to test this commit, https://github.com/utzcoz/robolectric-issue-5442-example.

**Comment by utzcoz** [comment]
> Hi @hoisie , I create a example app to test this commit, https://github.com/utzcoz/robolectric-issue-5442-example.

If I can't integrate AGP 7.1.0-alpha08 to ctesque correctly, I want to know whether we can merge this commit directly with this outer test app, and keep ctesque's test method ignored.

**Comment by utzcoz** [comment]
I found this article https://stefma.medium.com/its-time-to-ditch-the-buildscript-block-a1ab12e0d9ce, that provides a method to specify different plugin version for different modules.

**Comment by utzcoz** [comment]
> I found this article https://stefma.medium.com/its-time-to-ditch-the-buildscript-block-a1ab12e0d9ce, that provides a method to specify different plugin version for different modules.

I have tried this article's method, but AGP tells me that `Plugin request for plugin already on the classpath must not include a version`, although I tried to use `resolutionStrategy` to apply AGP version dynamically. Looks like if we want to use higher version AGP, we should bump it from `classpath`, including `build.gradle` and `buildSrc`.

**Comment by utzcoz** [comment]
> > AGP 7.1.0-alpha08 is released, I will try to integrate it to this PR to test `noCompress` support.
> 
> I use test app to test 7.1.0-alpha08, and its `noCompress` support works fine. But it is difficult to integrate AGP 7.1.0-alpha08 to ctesque. I have tried to use new AGP version for ctesque only, but it is omitted, because it is a library for entire project, and its AGP version is replaced by `buildSrc` and project configuration. The AGP 7.1.0-alpha08 needs gradle 7.1.0, and gradle 7.1.0 will cause testapp's class not found problem when running test. Hi @hoisie , do you have any suggestion for this integration problem? Thanks.

With more investigating, I think I fixed those build problems when bumping AGP to 7.1.0-alpha08. There are some things should be changed for AGP 7.1.0-alpha08:

1. Replace `testRuntime` with `testRuntimeOnly`(https://developer.android.com/studio/releases/gradle-plugin#dependency-configurations-removed).
2. Remove `configuration` when adding `testapp` as dependencies(maybe related to https://developer.android.com/studio/releases/gradle-plugin#variant-api-stable).
3. Add guava and jetbrains annotations with `api` for `buildSrc` explicitly(maybe related to https://developer.android.com/studio/releases/gradle-plugin#classpath-change).
4. Use JDK 11 to build and run tests for Robolectric.

AGP 7.1.0-alpha8 supports to change compatibility target to 11(https://developer.android.com/studio/releases/gradle-plugin#java-11) to leverage JDK 11 features, but it also support JDK 8 backward compatibility, and `RoboJavaModulePlugin` uses compatibility target 8, and I think final generated Robolectric jars has the same compatibility support as before, but it maybe needs more tests. Hi @hoisie , I only find the method to use AGP 7.1.0-alpha08 with upgrading all Robolectric's AGP version to  7.1.0-alpha08, and some tries tell me that gradle doesn't support multiple versions of plugin used by `classpath`. If you have more proper method for integrating AGP 7.1.0-alpha08, you can just leave it with comment, and I will try it. I think current PR reaches the reviewed state, could you help to review it? Thanks.

**Comment by utzcoz** [comment]
Hi @hoisie , could you help to review this PR? Thanks.

**Comment by xunkai55** [comment]
Friendly ping @hoisie :-)

**Comment by xunkai55** [comment]
Just a curious question: Stepping back, I wonder can we fix FileMap without bumping up the AGP version? The bug I encountered is with Bazel + Robolectrics, and I don't know if AGP is playing a part of that.

**Comment by hoisie** [comment]
AGP has nothing to do with Bazel.

**Comment by xunkai55** [comment]
Thanks for the clarification, @hoisie !

**Comment by utzcoz** [comment]
Bump AGP to 7.1.0-alpha11, and gradle to 7.2 for new AGP version.

**Comment by utzcoz** [comment]
Bump AGP to 7.1.0-alpha12.

**Comment by hoisie** [comment]
Looking into this, sorry for the delay.

**Pull request merged**
