### PR TITLE
MessageQueue - cache method and field lookups

### PR DESCRIPTION
**Pull request by kriegfrj**
Save having to do the method/field lookup & set accessibility on every method invocation by caching & reusing the appropriate method & field objects. Haven't benchmarked it but should improve performance a little.

### CODE REVIEW

**Comment by lexs** [comment]
I don't want to be pessimistic but I doubt this will measurable improve performance. Reflection is generally cached and access checks are done on each invocation anyways.

**Comment by kriegfrj** [comment]
Yeah, I didn't think it would set the world on fire, but I couldn't see it hurting. And does it still do access checks if you've already called `setAccessible(true)` on the reflection object?

Do you think that using `MethodHandle`s instead would be better? I started looking into it for the first time last night as I hadn't really understood what it was all about, but as I understand it the access checks are done once (if at all) when the handles are created. I haven't looked into it enough to figure out if you can use them to circumvent the access protection but

**Comment by lexs** [comment]
Yes, `setAccessible(true)` simply flips a boolean. The access checking is one of the reasons why `MethodHandle` was created. With that said however, method handles are not very fast in JDK7 (they are in 8 though), which makes things tricky.

If possible try to write a benchmark, I have a branch I could publish that adds a robolectric-benchmark project.

**Comment by erd** [comment]
> I have a branch I could publish that adds a robolectric-benchmark project.

I'd like to take a look at it, if you don't mind putting it up on github.

**Comment by kriegfrj** [comment]
Me too. I often wonder about the performance impact of changes that I make (especially when working on something pretty core like scheduling). I'm often just relying on educated (and sometimes not-that-well-educated :wink:) guesses - it would be good to have a more quantitative measure which I am too ~~lazy~~busy to implement myself.

**Comment by lexs** [comment]
Here is the branch: https://github.com/lexs/robolectric/tree/benchmarks/robolectric-benchmarks

Running a benchmark can be done with `java -cp target/benchmarks.jar org.robolectric.benchmark.UriBench`. Note that some of these use a bootstrap test to be able to run within the Robolectric environment.

**Comment by erd** [comment]
@kriegfrj Given @lexs comments above about performance, do you still want me to merge this?

**Comment by kriegfrj** [comment]
I haven't had a chance to benchmark it, but I don't really mind one way or the other @erd. Might as well leave it out if that makes things simpler. I'll probably end up changing that code anyway as part of #1879.

**Pull request closed without merging**
