### PR TITLE
Migrate tests from ShadowResourcesTest to ResourcesTest

### PR DESCRIPTION
**Pull request by utzcoz**
Only migrating tests have `to-do` flag. It also removes unused resources after migration.

### CODE REVIEW

**Comment by utzcoz** [comment]
Hi @hoisie , could you help to review this PR? Thanks.

**Comment by utzcoz** [comment]
Rebased on current master branch.

**Comment by utzcoz** [comment]
Rebased on current master branch. Hi @hoisie , could you help to review this PR? Thanks.

**Comment by hoisie** [comment]
Thanks!

**Pull request merged**
