### PR TITLE
Reformat Java files in the whole project

### PR DESCRIPTION
**Pull request by MGaetan89**
Following the merge of #9201, this PR reformats the whole project to adhere to `google-java-format` 1.22.0.

I used the following commands to reformat the project:
```bash
find . -name "*.java" -type f -print | xargs java -jar google-java-format-1.22.0-all-deps.jar -i
```

@hoisie I've reverted the changes in `processor/src/test/resources` as you suggested. If you see other files that shouldn't be modified, let me know.

> [!NOTE]
> It is currently in draft, so it can be tested internally at Google first, as suggested here: https://github.com/robolectric/robolectric/issues/9163#issuecomment-2175503158

### CODE REVIEW

**Comment by MGaetan89** [comment]
@brettchabot it's also being discussed in the corresponding issue: https://github.com/robolectric/robolectric/issues/9163
If you'd prefer moving forward with an other approach, I'm fine with that. I can imagine that synching such a big PR between branches might be complicated.

**Comment by hoisie** [comment]
@brettchabot I think this is a good change, even if it could cause some short term pain, i.e. merge conflicts. We often run into issues where people make a small change, and they reformat an entire file, which causes history to be a little confusing.

For example I ran into 1ffda0b25760555b6f330b7c735b2d0f581a76ff, and it is hard to tell what the actual change is, and what the whitespace is.

@MGaetan89 I am back from vacation and will see if the Google Linter will complain about this tomorrow.

**Comment by MGaetan89** [comment]
I've updated to PR to include the latest changes

**Comment by MGaetan89** [comment]
I've updated the PR to fix the latest conflicts

**Review by hoisie — APPROVED** [review]
I have tested this and the formatting is consistent with the google-java-format version used internally at Google, so it shouldn't cause any thrashing issues.

Can you please rebase, some files (e.g. StrfTime and ShadowWranglerIntegrationTest) have been changed.

**Comment by MGaetan89** [comment]
Sure, the PR is up to date now 🙂

**Comment by hoisie** [comment]
Thanks!

**Pull request merged**
