### PR TITLE
Shadow notification content text sub text

### LINKED ISSUE #2470: ShadowNotifiction#getContentText() returns SubText if notification object has one.
### Description

The implementation of ShadowNotifiction#getContentText relies on the TextView having the id "id.text". I found that was not true if Sub Text is set on the notification. In this case, the Sub Text gets "id.text" and the Content Text gets the id "id.text2".
### Steps to Reproduce

After a test failing after the update  https://github.com/robolectric/robolectric/commit/9d68c9a82b0c22bb716270222ec8174a1da48eaf
 I used hierarchyviewer to verify the id issue on a device running Lollipop.

### PR DESCRIPTION
**Pull request by jy-z-cheng**
### Overview

ShadowNotifiction#getContentText() returns subtext if subtext is set in the Notification. (fixes #2470)

There are three scenarios:
1. If only **contentText** is set, the content text is set to the texview with "R.id.text"
2. If both **contentText** and **subText** are set, the sub text is set to the texview with "R.id.text" and  the content text is set to the texview with "R.id.text2"
3. If only **subText** is set, the sub text is set to the texview with "R.id.text"

It does not seem like there is an easy way to distinguish 1 and 3 without shadowing the Notification.Builder.
### Proposed Changes

Since we have just moved away from shadowing the notification builder, I propose that we change ShadowNotification#getContentText to getCombinedContentText to return both content text and sub text.

### CODE REVIEW

**Comment by xian** [comment]
I think similar functionality has already been added, right @jongerrish?

**Comment by jy-z-cheng** [comment]
@xian, @jongerrish fixed ShadowNotification for Nougat, but the current implementation of ShadowNotification still does not support subText and "R.id.text2" when both contentText and subText is set. 

Since this PR is based on an older implementation of ShadowNotification, it may be easier for me to reimplement it from scratch, but I am not sure when I will get around to it. Should I close this PR for now and reopen it when the conflicts are resolved?

**Comment by jongerrish** [comment]
Can you just rebase onto master and resolve the conflict?

**Comment by pivotal-james-zcheng** [comment]
@jongerrish, sorry for the long delay. I've rebased and resolved the conflict. However, I still need to reimplement my changes for N+ tests. I am in the progress of doing that.

**Comment by pivotal-james-zcheng** [comment]
@jongerrish To prevent introducing API breaking changes, I did not rename `getContentText` in my PR. However, that name is inaccurate as it returns both contentText and subText. Should I change it to `getCombinedContentText"?

**Comment by jongerrish** [comment]
Yeah, but keep the original and #Deprecate so we don't break anyone 😃

**Comment by pivotal-james-zcheng** [comment]
@jongerrish Okay. Done. 

Also, I noticed there is a mix of `RuntimeEnvironment.getApiLevel()` vs `getApiLevel() and `Build.VERSION_CODES.N` vs `N` in ShadowNotification. What is our preference on static imports? Should I make it consistent? In this PR or open a new one?

**Comment by utzcoz** [comment]
@jy-z-cheng Thanks for your contribution. But this PR is too old, please rebase to the latest master branch and reopen it again if you still want us to merge this PR. Thanks.

**Pull request closed without merging**
