### PR TITLE
Extending shadow of AccessibilityNodeInfo

### PR DESCRIPTION
**Pull request by yuzhong-google**
Complementing ShadowAccessibilityNodeInfo logic.

### CODE REVIEW

**Comment by erd** [comment]
I'd prefer if you move the `RuntimeEnvironment` changes to a new PR, since it doesn't have anything to do with the changes to `ShadowAccessibilityRecord`.

**Comment by yuzhong-google** [comment]
@erd , will do, thanks!

**Comment by yuzhong-google** [comment]
@erd, separated changes into 2 PRs.

**Comment by erd** [comment]
Thanks!

**Pull request merged**
