### PR TITLE
Revert "Modified the resolution of resource folders to a local context"

### PR DESCRIPTION
**Pull request by rogerhu**
This reverts commit 8676da2daa4c140679fb5903696b8191415cec8f.

See https://github.com/robolectric/robolectric/issues/2096

### CODE REVIEW

**Comment by rogerhu** [comment]
Thanks!  Can we get a new snapshot build?

**Comment by erd** [comment]
It should be build automatically by the CI build.

**Comment by rogerhu** [comment]
That's what I thought but looking at https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/robolectric/3.1-SNAPSHOT/ the last build was on 10/29?

**Comment by ened** [comment]
@erd the snapshot builds are not refreshing right now?

**Pull request merged**
