### PR TITLE
Use compat-target module to test compatibility from SDK 28

### PR DESCRIPTION
**Pull request by utzcoz**
To test https://github.com/robolectric/robolectric/issues/7095.

### CODE REVIEW

**Review by hoisie — COMMENTED** [review]
Want to commit this? Pretty soon we will hopefully be able to catch issues like this using the annotation validator.

**Comment by utzcoz** [comment]
> Want to commit this? Pretty soon we will hopefully be able to catch issues like this using the annotation validator.

Looks like this PR can't catch issue correctly. The problem reported by related issue exists, and the fixed `SplashScreen` compatibility problem is the same as this problem. But this PR can't report any problem of `Font` compatibility problem. I decide to investigate it more to find root cause. We can discuss whether to check it in after that.

**Comment by utzcoz** [comment]
Looks like Robolectric loads `org.robolectric:android-all-instrumented:12.1-robolectric-8229987-i4` too for `compat-target28` module.

**Comment by utzcoz** [comment]
Oh, I think I found the root cause: the Kotlin and Java have different behavior to loading class in another class. If I write test with Kotlin with compileSdk 28, the test will pass without any error. But if I write the same test with Java, it will raise "X not found" exception. Not only `Font` class not found, but also `RoleManager` not found when testing `shadowOf` with compileSdk 28.

**Comment by utzcoz** [comment]
> Oh, I think I found the root cause: the Kotlin and Java have different behavior to loading class in another class. If I write test with Kotlin with compileSdk 28, the test will pass without any error. But if I write the same test with Java, it will raise "X not found" exception. Not only `Font` class not found, but also `RoleManager` not found when testing `shadowOf` with compileSdk 28.

@hoisie We can see the following exception with latest commit on CI:

```
2022-05-15T14:41:03.8610795Z :integration_tests:compat-target28:compileDebugUnitTestKotlin (Thread[Execution worker for ':',5,main]) completed. Took 13.215 secs.
2022-05-15T14:41:03.8611617Z :integration_tests:compat-target28:compileDebugUnitTestJavaWithJavac (Thread[Execution worker for ':',5,main]) started.
2022-05-15T14:41:04.3609233Z /home/runner/work/robolectric/robolectric/integration_tests/compat-target28/src/test/java/org/robolectric/integration/compat/target28/JavaClassResolveCompatibilityTest.java:29: error: cannot access RoleManager
2022-05-15T14:41:04.3609749Z 
2022-05-15T14:41:04.3610026Z     ShadowApplication shadowApplication = Shadows.shadowOf(application);
2022-05-15T14:41:04.3610408Z                                                  ^
2022-05-15T14:41:04.3610771Z   class file for android.app.role.RoleManager not found
2022-05-15T14:41:04.3611091Z 1 error
```

**Comment by utzcoz** [comment]
I add `Ignore` to related test to prevent it running to ensure this PR can be merged. And the `Ignore` can be removed when working on `improving shadowOf generation` or related compatibility problems.

**Comment by utzcoz** [comment]
Hi @hoisie , do you think it is comfortable to merge? Thanks.

**Comment by utzcoz** [comment]
> Hi @hoisie , do you think it is comfortable to merge? Thanks.

Friendly ping @hoisie could you help to review this PR? Thanks.

**Review by hoisie — APPROVED** [review]

**Pull request merged**
