### PR TITLE
@Config(packageName = "...") should also set Context.getPackageName()

### PR DESCRIPTION
**Pull request by jongerrish**

### CODE REVIEW

**Comment by cesar1000** [comment]
Jonathan, I found that this is the patch that's making our tests fail in 3.1. We are using the system properties to set the location of the manifest, assets and resources from our gradle scripts (since RobolectricGradleTestRunner is restrictive for our needs). What's the reason for removing the system properties?

I can try to extend RobolectricGradleTestRunner to work for our needs if that's the preferred solution though.

**Comment by jongerrish** [comment]
The reason was code simplification and because I suspected no one was using them anymore (most use Gradle test runner). We can add them back in though as we're thinking about using system properties for the build systems to interact with the test runner going forward.

Which ones specifically do you need?

**Comment by cesar1000** [comment]
We are using "android.manifest", "android.assets" and "android.resources". I like the idea of delegating on the build system the responsibility of configuring Robolectric, instead of letting the Robolectric runner figure out the paths itself. The latter is tricky, since generated files are temporary, and newer versions of the plugin may place them in new locations.

In our case, we are running special resource processing and asset merge tasks to collect assets and resources from all dependencies (instead of using solely the assets and resources in the library)

**Comment by jongerrish** [comment]
Interesting, so you're saying Gradle doesn't do resource and manifest merging of all transitive dependencies before the test? Sounds like you're doing the same thing we are. We will add these system properties as the preferred interface between the runner and build system.

**Comment by cesar1000** [comment]
Ah, I didn't check manifest merging. In the case of a library, it certainly doesn't do asset and resource merging from transitive dependencies, since the library only packages its own resources. Applications are fine though. I filed a ticket about that, where I describe my (hacky) workaround for that: https://code.google.com/p/android/issues/detail?id=211351. Fixing directly in the Android gradle plugin should be much easier!

Bringing back those properties sounds great. You could also provide a gradle plugin to set these properties. They plugin may just use doFirst on all unit test tasks, which would remove the need to look up the BuildConfig class.

**Pull request merged**
