### PR TITLE
Implement Choreographer.removeFrameCallback()

### PR DESCRIPTION
**Pull request by lexs**

### CODE REVIEW

**Comment by kriegfrj** [comment]
Hmm, I'm not sure that this is the best implementation. I think that ideally `ShadowChoreographer` should be implemented to post through its `Handler/Looper` rather than posting to `Scheduler` directly. This is what real Android does (IIRC) - in fact, you might be able to remove these shadow implementations and let the real Android code handle it. `Looper` already support the extra token handling and changes to `Scheduler` would not have been necessary. Thoughts?

**Comment by lexs** [comment]
Didn't know that tokens where respected for Handlers but if that works that it obviously a better implementation. If so removing the token handling from Scheduler makes sense.

**Comment by kriegfrj** [comment]
Yeah, tokens weren't always respected by Robolectric's `Handler` implementation, but I needed this for the `ShadowMediaPlayer` changes I implemented so I added it fairly recently (#1431, #1466). It should be a fairly trivial change to refactor it to use `Handler` instead.

Actually, there are a lot of conceptual similarities between `ShadowMediaPlayer` and `ShadowChoreographer`, as they both deal with scheduling & playback of events - it might be worth us keeping an eye on them and see if there is a chance to abstract some of it out into a common utility class.

**Comment by lexs** [comment]
I've fixed this in https://github.com/robolectric/robolectric/pull/1812

**Pull request merged**
