### PR TITLE
Generic build system support

### PR DESCRIPTION
**Pull request by xian**
Allow arbitrary build systems to pass configuration information to Robolectric, as described here: http://robolectric.org/build-system-integration/

### CODE REVIEW

**Comment by marcinkosiba** [comment]
Thanks for working on this! For buck I think it would be to our advantage to keep the ability to do the resource merging in robolectric.

In buck we encourage more smaller targets over fewer bigger ones and so in one of our repositories we have about 2k robolectric_test targets. These robolectric targets represent tests for particular modules; most of the time these modules are independent of the app they run in, therefore the tests for these modules work as if we were testing a small sample app that only contains that module and its transitive dependencies.

The above means that, for every one of the 2k tests we have a different classpath, set of resources, assets and a different R.java class. Buck already takes care of the R.java class and Manifest. 

Merging assets could be done using a symlink tree (so we would only re-do it when the user adds/removes files, but not when they edit), but for resources we can't do anything like that.

**Comment by dreiss** [comment]
@marcinkosiba on the other hand, we're already paying a steep cost during Robolectric startup to process all of these resources, right?  If that work could be moved into the build phase and cached, we might get a net win.

I guess one benefit of doing it at runtime is that it can be done lazily, so tests that don't use resources don't need to pay the cost at all.

**Comment by dreiss** [comment]
Talking about this a bit more with @kageiit , I'm more concerned about the performance now.  If we have 2k test targets (from Martin's number), with an average of 5k transitively included resources (I made this number up based on what our app looks like), that's 10,000,000 symlinks that need to be created in the filesystem, which takes quite some time even with the build cache.

I guess what we'd want is to still have the option of passing multiple resource directories, and have Robolectric lazily look up the resources (since I suspect most tests won't access very many).  Is that reasonable to support?

**Comment by marcinkosiba** [comment]
@dreiss I don't think the resource merging changes the amount of data you need to read. Maybe it removes some overrides, but by merging you go from having to read many small files to fewer big files, while the overall amount of data remains roughly the same,

IIRC Gradle resource merging works by reading a bunch of .xml files and writing out new ones, I'm not sure what symlink trickery you propose, but if we're not modifying the .xml files, then surely you'd end up doing the same amount of work as in the case without merging?

If we want to squeeze out more perf perhaps a more useful thing the build system could provide is some form of index? I imagine if there is a slow part to this, it's parsing the values.xml files in search of the right value? I haven't profiled robolectric resource code, perhaps @xian can shed some light on how worthwhile this would be?

**Comment by jongerrish** [comment]
Having resource merging done by the build system is the direction we want to go because each build system uses a different merging strategy. Build systems will fail when there are resource clashes that need fixing so this would be caught early at build time of the tests. Robolectric has a very rudimentary merging strategy that is not going to merge resources the same way as would be done for your app and it won't catch these clashes and may potentially give you different resources than you would expect leading to inaccurate tests. The build system should be incremental as well so the merging cost is not paid every time you run a test - not that I think the merging cost in Robolectric is high, but still. We are interested in building on this to read the indexed arsc files directly at some point which would be faster and less buggy that trying to mimic aapt code ourselves but that needs resource merging to be in place anyway.

We are making changes at the moment to the package manager which would defer manifest parsing until it is accessed which would also mean we could defer resource loading (e.g: resources need to be loaded if the manifest has any resource references).

We really want to remove manifest = Config.NONE and always provide Robolectric the resources if they are present in the transitive closure. Config.NONE is bad because if any code paths in your dependencies change to access resources your tests will suddenly fail.

**Pull request merged**
