### PR TITLE
Use prebuilt Robolectric Native Runtime artifacts from AOSP

### PR DESCRIPTION
**Pull request by hoisie**
Previously, the Robolectric Native Runtime (RNR), which only contained
Android SQLite, was built in a git/Gradle environment using CMake and
Git submodules for SQLite and ICU. There were complex workflows needed
to build RNR on different platforms and package artifacts into an uber
Jar.

Over the past year, we created a custom AOSP branch derived from Android
S (android12-hostruntime-dev) that can build native Android libraries
for host. Using this approach we have enabled running native Android
graphics libraries for Robolectric in addition to SQLite.

Switch to include RNR from a prebuilt uber Jar that is built from this
custom AOSP branch. This will significantly simplify the Robolectric
development environment and CI as it will not require building native
code any more.

Because these native libraries also contain graphics code, using
`@GraphicsMode(NATIVE)` is also possible after this change. Some
forthcoming commits will add a large suite of graphics tests to
Robolectric.

The development of these native libraries will be decoupled from the
Java sources of Robolectric. Starting in Android U or V, however, the
plan is to have each Android-all platform Jar also contain the relevant
native code for that platform to maximize fidelity, so building these
native libraries will be more or less opaque to Robolectric (similar to
how the platform jars are built).

### CODE REVIEW

**Review by utzcoz — APPROVED** [review]

**Comment by utzcoz** [comment]
@hoisie What about merging it? We can start to update documentation about Robolectric's building.

**Comment by hoisie** [comment]
sounds good, I will merge and then try to push out 4.10-alpha-1

**Comment by utzcoz** [comment]
Will https://github.com/robolectric/robolectric/pull/7997 be merged before 4.10-alpha-1?

**Comment by hoisie** [comment]
There is some demand for native graphics in a Gradle/Maven environment, so I may have to do it before. FWIW all of the tests pass on my local machine, it's just a small matter of time until the tests get moved to here.

**Pull request merged**
