### PR TITLE
[warning] UnusedMethod warning fix

### PR DESCRIPTION
**Pull request by hellosagar**
### Overview
[UnusedMethod](https://errorprone.info/bugpattern/UnusedMethod) - Unused.

### Proposed Changes
Removed the unused methods.

### CODE REVIEW

**Comment by utzcoz** [comment]
@hellosagar Could you squash commits to one? Thanks.

**Review by utzcoz — APPROVED** [review]
LGTM. Thanks.

**Comment by utzcoz** [comment]
I need internal validation feedback from @hoisie or @JuliaSullivanGoogle before merging.

**Comment by JuliaSullivanGoogle** [comment]
> I need internal validation feedback from @hoisie or @JuliaSullivanGoogle before merging.

I did a quick "Find Refernces" on the prinf function and it came up with nothing. What a bizzare file 0.0

**Comment by utzcoz** [comment]
@JuliaSullivanGoogle Thanks.

**Pull request merged**
