### PR TITLE
Add android.opengl.Matrix shadow for native methods

### PR DESCRIPTION
**Pull request by korniltsev**

### CODE REVIEW

**Comment by jongerrish** [comment]
Hey, thanks for the contribution! :-)

We actually have an internal version of this Shadow I wanted to opensource, would you mind ensuring that the

**Comment by jongerrish** [comment]
Hey, thanks for the contribution! We actually have an internal version of this I was going to open source.... would you mind checking that the following test cases are included + pass and I'll go ahead and merge this!

  @Test
  public void testLength() {
    assertThat(Matrix.length(3, 4, 5)).isWithin(0.001f).of(7.071f);
  }

  @Test
  public void testInvertM() {
    float[] matrix = new float[] {
      10, 0, 0, 0,
      0, 20, 0, 0,
      0, 0, 30, 0,
      40, 50, 60, 1
    };

    float[] inverse = new float[] {
      0.1f, 0, 0, 0,
      0, 0.05f, 0, 0,
      0, 0, 0.03333f, 0,
      -4, -2.5f, -2, 1
    };
    float[] output = new float[16];
    assertThat(Matrix.invertM(output, 0, matrix, 0)).isTrue();
    assertThat(output).hasValuesWithin(0.001f).of(inverse);
  }

  @Test
  public void testMultiplyMM() {
    float[] matrix1 = new float[] {
      1, 2, 3, 4,
      5, 6, 7, 8,
      9, 10, 11, 12,
      13, 14, 15, 16
    };
    float[] matrix2 = new float[] {
      16, 15, 14, 13,
      12, 11, 10, 9,
      8, 7, 6, 5,
      4, 3, 2, 1
    };
    float[] expected = new float[] {
      386, 444, 502, 560,
      274, 316, 358, 400,
      162, 188, 214, 240,
      50, 60, 70, 80,
    };

    float[] output = new float[16];
    Matrix.multiplyMM(output, 0, matrix1, 0, matrix2, 0);
    assertThat(output).hasValuesWithin(0.001f).of(expected);
  }

  @Test
  public void testFrustumM() {
    float[] expected = new float[] {
      0.005f, 0, 0, 0,
      0, 0.02f, 0, 0,
      3, 5, -1.020202f, -1,
      0, 0, -2.020202f, 0,
    };
    float[] output = new float[16];
    Matrix.frustumM(output, 0, 100, 500, 200, 300, 1, 100);
    assertThat(output).hasValuesWithin(0.001f).of(expected);
  }

  @Test
  public void testPerspectiveM() {
    float[] expected = new float[] {
      1145.9144f, 0, 0, 0,
      0, 572.9572f, 0, 0,
      0, 0, -1.020202f, -1,
      0, 0, -2.020202f, 0,
    };
    float[] output = new float[16];
    Matrix.perspectiveM(output, 0, 0.2f, 0.5f, 1, 100);
    assertThat(output).hasValuesWithin(0.001f).of(expected);
  }

  @Test
  public void testMultiplyMV() {
    float[] matrix = new float[] {
      2, 0, 0, 0,
      0, 4, 0, 0,
      0, 0, 6, 0,
      1, 2, 3, 1
    };

    float[] vector = new float[] { 5, 7, 9, 1 };
    float[] expected = new float[] { 11, 30, 57, 1 };
    float[] output = new float[4];
    Matrix.multiplyMV(output, 0, matrix, 0, vector, 0);
    assertThat(output).hasValuesWithin(0.001f).of(expected);
  }

  @Test
  public void testSetIdentityM() {
    float[] matrix = new float[] {
      1, 2, 3, 4,
      5, 6, 7, 8,
      9, 10, 11, 12,
      13, 14, 15, 16
    };
    float[] expected = new float[] {
      1, 0, 0, 0,
      0, 1, 0, 0,
      0, 0, 1, 0,
      0, 0, 0, 1
    };
    Matrix.setIdentityM(matrix, 0);
    assertThat(matrix).hasValuesWithin(0.001f).of(expected);
  }

  @Test
  public void testScaleM() {
    float[] matrix = new float[] {
      1, 2, 3, 4,
      5, 6, 7, 8,
      9, 10, 11, 12,
      13, 14, 15, 16
    };
    float[] expected = new float[] {
      2, 4, 6, 8,
      20, 24, 28, 32,
      54, 60, 66, 72,
      13, 14, 15, 16
    };
    float[] output = new float[16];
    Matrix.scaleM(output, 0, matrix, 0, 2, 4, 6);
    assertThat(output).hasValuesWithin(0.001f).of(expected);
  }

  @Test
  public void testScaleMInPlace() {
    float[] matrix = new float[] {
      1, 2, 3, 4,
      5, 6, 7, 8,
      9, 10, 11, 12,
      13, 14, 15, 16
    };
    float[] expected = new float[] {
      2, 4, 6, 8,
      20, 24, 28, 32,
      54, 60, 66, 72,
      13, 14, 15, 16
    };
    Matrix.scaleM(matrix, 0, 2, 4, 6);
    assertThat(matrix).hasValuesWithin(0.001f).of(expected);
  }

  @Test
  public void testTranslateM() {
    float[] matrix = new float[] {
      1, 2, 3, 4,
      5, 6, 7, 8,
      9, 10, 11, 12,
      13, 14, 15, 16
    };
    float[] expected = new float[] {
      1, 2, 3, 4,
      5, 6, 7, 8,
      9, 10, 11, 12,
      89, 102, 115, 128
    };
    float[] output = new float[16];
    Matrix.translateM(output, 0, matrix, 0, 2, 4, 6);
    assertThat(output).hasValuesWithin(0.001f).of(expected);
  }

  @Test
  public void testTranslateMInPlace() {
    float[] matrix = new float[] {
      1, 2, 3, 4,
      5, 6, 7, 8,
      9, 10, 11, 12,
      13, 14, 15, 16
    };
    float[] expected = new float[] {
      1, 2, 3, 4,
      5, 6, 7, 8,
      9, 10, 11, 12,
      89, 102, 115, 128
    };
    Matrix.translateM(matrix, 0, 2, 4, 6);
    assertThat(matrix).hasValuesWithin(0.001f).of(expected);
  }

  @Test
  public void testRotateM() {
    float[] matrix = new float[] {
      1, 2, 3, 4,
      5, 6, 7, 8,
      9, 10, 11, 12,
      13, 14, 15, 16
    };
    float[] expected = new float[] {
      0.95625275f, 1.9625025f, 2.968752f, 3.9750016f,
      5.0910234f, 6.07802f, 7.0650167f, 8.052013f,
      8.953606f, 9.960234f, 10.966862f, 11.973489f,
      13, 14, 15, 16
    };
    float[] output = new float[16];
    Matrix.rotateM(output, 0, matrix, 0, 2, 4, 6, 8);
    assertThat(output).hasValuesWithin(0.001f).of(expected);
  }

  @Test
  public void testRotateMInPlace() {
    float[] matrix = new float[] {
      1, 2, 3, 4,
      5, 6, 7, 8,
      9, 10, 11, 12,
      13, 14, 15, 16
    };
    float[] expected = new float[] {
      0.95625275f, 1.9625025f, 2.968752f, 3.9750016f,
      5.0910234f, 6.07802f, 7.0650167f, 8.052013f,
      8.953606f, 9.960234f, 10.966862f, 11.973489f,
      13, 14, 15, 16
    };
    Matrix.rotateM(matrix, 0, 2, 4, 6, 8);
    assertThat(matrix).hasValuesWithin(0.001f).of(expected);
  }

  @Test
  public void testSetRotateM() {
    float[] matrix = new float[] {
      1, 2, 3, 4,
      5, 6, 7, 8,
      9, 10, 11, 12,
      13, 14, 15, 16
    };
    float[] expected = new float[] {
      0.9998687f, 0.01299483f, -0.00968048f, 0,
      -0.012931813f, 0.999895f, 0.006544677f, 0,
      0.009764502f, -0.006418644f, 0.99993175f, 0,
      0, 0, 0, 1
    };
    Matrix.setRotateM(matrix, 0, 1, 2, 3, 4);
    assertThat(matrix).hasValuesWithin(0.001f).of(expected);
  }

**Comment by korniltsev** [comment]
There was a bug in frustum's method.
See 
http://code.google.com/p/android/issues/detail?id=35646
https://android.googlesource.com/platform/frameworks/base/+/0a088f5d4681fd2da6f610de157bf905df787bf7

**Comment by jongerrish** [comment]
Sorry, I didn't mean to close this PR.

**Pull request closed without merging**
