### PR TITLE
#1959 - Added SupportFragmentController

### PR DESCRIPTION
**Pull request by andrewlord1990**
There is a FragmentController for Fragments, however, there was no controller for support-v4 Fragments. This has been added.

It is in the shadows-support-v4 module.

It is in the org.robolectric.util package so that it can extend ComponentController (which has package level visibility).

### CODE REVIEW

**Comment by erd** [comment]
Could you reformat this with a 2 space indent?

**Comment by andrewlord1990** [comment]
I have done the reformat.

**Comment by jaredsburrows** [comment]
@andrewlord1990  +1

**Comment by erd** [comment]
Thanks for the PR! I went ahead and moved the class into the `org.robolectric.shadows.support.v4` package with the rest of the support-v4 shadows and increased the visibility of `ComponentController`.

**Pull request closed without merging**
