### PR TITLE
[utils module] [Test conversion] Service finder adapter test

### PR DESCRIPTION
**Pull request by hellosagar**
### Overview
Converted the [MyServiceFinderAdapter](https://github.com/hellosagar/robolectric/blob/2ec23249c160bcb10a4a5024cad142f835fddda0/utils/src/test/java/org/robolectric/util/inject/MyServiceFinderAdapter.kt)  from java to kotlin

### Proposed Changes
In this, I've basically removed the java version `MyServiceFinderAdapter` and added the kotlin version

### CODE REVIEW

**Comment by hellosagar** [comment]
Is there is way to re-run the GitHub actions on this PR besides doing a force commit again 😅, I'm my own repo's I can re-run GitHub actions and I think one action is canceled but can be fixed just by re running it.

**Comment by utzcoz** [comment]
> Is there is way to re-run the GitHub actions on this PR besides doing a force commit again sweat_smile, I'm my own repo's I can re-run GitHub actions and I think one action is canceled but can be fixed just by re running it.

You can click details of failed task to enter running page, and click "re-run" related button to re-run your failed task. Current GitHub Actions support to run failed task only, instead of all tasks.

**Comment by hellosagar** [comment]
There is no re-run button here 
Screenshot 2022-04-16 at 1 16 01 PM

**Comment by utzcoz** [comment]
Looks like you don't have permission to see it. I re-run failed job for you.

**Review by hoisie — APPROVED** [review]

**Comment by hellosagar** [comment]
Rebased.

**Comment by hellosagar** [comment]
sheh

**Comment by hellosagar** [comment]
I forget to check the spotless on every commit, on every commit before committing the changes I will check if there is a way to run the checks

**Comment by hellosagar** [comment]
I think pre-commits will do the job for me

**Review by utzcoz — APPROVED** [review]

**Pull request merged**
