### PR TITLE
All test methods run in the same thread

### LINKED ISSUE #6105: Robolectric runs @AfterClass methods on different thread than @BeforeClass methods, test methods
### Description
While `@BeforeClass ` methods and test methods are executed on the same thread as the main looper, `@AfterClass` methods are executed on a different thread. This is causing issues with mockk who (reasonably) scopes mocks with thread local values. Mocking and unmocking classes takes a significant chunk of time, so it would beneficial to be able to do it before class and after class. 

Robolectric's current threading approach makes this difficult since unmocking on a separate thread has no effect. With the new PAUSED LooperMode, posting this statement to the main thread also has no effect because there is no way to way to drain the main queue from this other thread. 

Mockk issue: https://github.com/mockk/mockk/issues/548

### Steps to Reproduce
```
@RunWith(AndroidJUnit4::class)
class ExampleTest {

    @Test
    fun test1() {
        assertThat("1").isEqualTo("1")
    }

    companion object {

        @JvmStatic
        @BeforeClass
        fun setupClass() {
            println("BeforeClass thread=${Thread.currentThread()}")
        }


        @JvmStatic
        @AfterClass
        fun afterClass() {
            println("AfterClass thread=${Thread.currentThread()}")
        }
    }
}
```

### Robolectric & Android Version

Robolectric: 4.3.1
Android sdk: 28

### PR DESCRIPTION
**Pull request by LitterSun**
Fixes #6105

### CODE REVIEW

**Comment by hoisie** [comment]
Thank you for investigating and doing this. Overall this looks fine to me, I am running this one some tests internally to see if it catches any potential issues.

**Comment by alsutton** [comment]
What would happen here if the main thread gets blocked? I'm wondering if this PR would create a change in behaviour where, for a test that's blocked, the clean-up would no longer run and therefore subsequent tests would be affected by the state changes for the test which became blocked.

**Comment by hoisie** [comment]
Doesn't the code wait for all tests in a suite to complete before running the `@AfterClass` method? So if a test blocks, will the `@AfterClass` get run?

Overall I'm fine with this change, seems better to have thread consistency.

**Comment by alsutton** [comment]
You're right, my bad, I read around the change and saw the sandbox creation code which will isolate any runner instance from other runners. I'm always wary of moving things onto the main thread because of the potential to block everything, in this case unnecessarily so. 

Apologies for the confusion @hoisie

**Pull request merged**
