### PR TITLE
Switch to run tests on Emulator with SDK 29,32

### PR DESCRIPTION
**Pull request by utzcoz**
It's time to run tests on Emulator with images targeted to newer SDKs.

### CODE REVIEW

**Comment by utzcoz** [comment]
Looks like there are not existing google_images with SDK 32, so switch to use 31 firstly.

**Comment by utzcoz** [comment]
Looks like from Android 12, there only exists x86_64 images with Google APIs. I should select different architecture for it.

**Comment by utzcoz** [comment]
Those tests failed on official Emulator with SDK 32 images, but they can pass on Emulator built from Android 12L source code locally.

**Comment by utzcoz** [comment]
I used Android 12L r1 source code to build Emulator, and it didn't have this restriction for `MotionEvent`. @hoisie Will this restriction be included from later releases? Does Android 12L images with Google APIs use internal/later release source code to build images? I  will test it with master branch source code.

**Comment by hoisie** [comment]
cc @brettchabot 

@utzcoz I am not too familiar with MotionEventTest

Should we file a bug against Android?

**Comment by utzcoz** [comment]
> cc @brettchabot
> 
> @utzcoz I am not too familiar with MotionEventTest
> 
> Should we file a bug against Android?

Those tests also can pass on today's master branch AOSP, but its cts test suite has updated for this restriction. I will file a bug on issue-tracker.

**Comment by utzcoz** [comment]
@hoisie File a new bug at issuetracker: https://issuetracker.google.com/issues/226640821, and wait for product team's response.

**Comment by utzcoz** [comment]
I give up to integrate AVD cache with unexpected error, and add gradle cache for instrumentation-test at this PR.

**Comment by utzcoz** [comment]
> I give up to integrate AVD cache with unexpected error, and add gradle cache for instrumentation-test at this PR.

Thanks https://github.com/robolectric/robolectric/pull/7195 to enable cache for AVD, and I reuse it for new SDK.

**Comment by utzcoz** [comment]
@hoisie Should I copy test from non pointer source for offsetLocation from official CTS test case?

**Review by hoisie — APPROVED** [review]

**Comment by hoisie** [comment]
@utzcoz up to you, I'll try to get more visibility to that bug

**Comment by utzcoz** [comment]
> @utzcoz up to you, I'll try to get more visibility to that bug

I will file a new issue at Robolectric to track this bug, and add more tests from CTS' `MotionEventTest` at following PRs.

**Comment by utzcoz** [comment]
File a new issue at https://github.com/robolectric/robolectric/issues/7215.

**Pull request merged**
